### PR TITLE
Return an error when wallet is nil rather than panic

### PR DESCRIPTION
**Pull request by prestonvanloon**
**What type of PR is this?**

Other

**What does this PR do? Why is it needed?**

This will prevent a panic in the case that wallet is nil.

**Which issues(s) does this PR fix?**

Eel9-LCWkAQVfGK

**Other notes for review**

I am not sure how this wallet could be nil, but it has been reported on twitter.

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Duplicate of #6877

**Comment by terencechain** [comment]
> Duplicate of #6877

@prestonvanloon are we sure this is a duplicate? This panics here
https://github.com/prysmaticlabs/prysm/blob/master/validator/accounts/v2/wallet.go#L221

**Comment by prestonvanloon** [comment]
oh sorry, a bit tired

**Comment by prestonvanloon** [comment]
Please review @terencechain

**Pull request merged**
