### PR TITLE
Remove support for ropsten testnet

### PR DESCRIPTION
**Pull request by peterbitfly**
**What type of PR is this?**
Bug fix

**What does this PR do? Why is it needed?**
Currently prysm does not work together with geth v1.11.0 when used as a module. This is because prysm still maintains a config for the now obsolete ropsten testnet and imports some configuration details from geth. With geth v1.11.0 this definitions were removed and now prysm breaks the following error as soon as it is imported together with geth:

```
# github.com/prysmaticlabs/prysm/v3/config/params
../../pkg/mod/github.com/prysmaticlabs/prysm/v3@v3.1.1/config/params/testnet_ropsten_config.go:29:34: undefined: params.RopstenChainConfig
../../pkg/mod/github.com/prysmaticlabs/prysm/v3@v3.1.1/config/params/testnet_ropsten_config.go:30:36: undefined: params.RopstenChainConfig
```

This PR removes the `testnet_ropsten_config.go` configuration file together with all ropsten configuration options.

### CODE REVIEW

**Comment by nisdas** [comment]
Hey @peterbitfly , 

Thanks for opening this PR, to deprecate the testnet correctly, you will need to add it to the deprecated flags list. For an example of where we do this you can look at:
https://github.com/prysmaticlabs/prysm/pull/10522

**Comment by jclapis** [comment]
I'll add a +1, we just ran into this with the Rocket Pool stack. We're sticking to Geth v1.10.26 and Prysm v3.2.0 until it's resolved.

**Comment by nisdas** [comment]
@peterbitfly I was unable to push the changes to this branch, so I opened a new PR which has them here:
https://github.com/prysmaticlabs/prysm/pull/12058

**Comment by nisdas** [comment]
Closing this PR as #12058 has merged in.

**Pull request closed without merging**
