### PR TITLE
upgrading linter from gometalinter to golangci-lint

### LINKED ISSUE #2098: Update Travis to upgrade gometalinter to golangci-lint
Update .travis.yaml file to upgrade the linting from gometalinter to golangci-lint. 

[gometalinter](https://github.com/alecthomas/gometalinter) is now a deprecated project and all linting updates will to be moved from gometalinter to golangci-lint.

### PR DESCRIPTION
**Pull request by frederickalcantara**
TODO(you): choose "part of" or "resolves" and the associated github issue #.

Resolves #2098

---

# Description

**Write why you are making the changes in this pull request**

**Write a summary of the changes you are making**

**Link anything that would be helpful or relevant to the reviewers**

### CODE REVIEW

**Comment by prestonvanloon** [comment]
There is some error
```
Running error: context loading failed: failed to make build flags for go list: invalid modules download path readonly|release|vendor, only (release|readonly|vendor) allowed 
```

**Comment by frederickalcantara** [comment]
This is a possible solution. 

https://github.com/golangci/golangci-lint/issues/395

**Comment by frederickalcantara** [comment]
The travis build keeps on giving me this error: The command "golangci-lint run" exited with 1.
Which could be that tests weren't built for it. Other than that, the linting does the intended job it's supposed to do.

**Comment by nisdas** [comment]
@frederickalcantara this looks like its working now :smiley:  but we just want to enable the following linters, the same as before in gometaliner
```
      "deadcode",	
      "goconst",	
      "goimports",	
      "golint",	
      "gosec",	
      "gotype",	
      "misspell",	
      "structcheck",	
      "unparam",	
      "varcheck"
```

**Comment by frederickalcantara** [comment]
I enabled this, do you have any reason why the Travis build keeps on falling?

**Comment by nisdas** [comment]
@frederickalcantara thats because you also have other linters enabled such as `govet` and `gocritic` etc. which lead to the build failing. You have to disable those for the build to pass and only enable the one's I have pointed out above

**Comment by frederickalcantara** [comment]
@nisdas I enable the according linters and I still get that errors. I'm completely stuck, let me know if you have better luck getting it to work.

**Comment by frederickalcantara** [comment]
@nisdas I enabled the ones you specified and removed gotype because it kept on failing with gotype. I even added a fixed lint version as well and the build still fails.

**Comment by nisdas** [comment]
@frederickalcantara hey you can put back gotype in it, its failing because we have lint failures in our repo. metalinter is very inconsistent and usually doesn't run all the linters correctly so a lot of the errors are hidden. looks like golang-ci is able to bring all of them up. @prestonvanloon Should we merge this in ? we can handle the lint failure in another pr.

**Comment by frederickalcantara** [comment]
This new linter use typecheck rather than gotype

**Comment by frederickalcantara** [comment]
I got this error when adding gotype. ERRO Running error: no such linter "gotype

**Comment by nisdas** [comment]
Alright in that case typecheck is fine

**Comment by frederickalcantara** [comment]
This is the error they had always occurred. The command "golangci-lint run" exited with 1.

**Comment by prestonvanloon** [comment]
We should handle lint issues in this PR. I can help fix them tomorrow

**Comment by nisdas** [comment]
please remove the golangci-lint binary

**Comment by frederickalcantara** [comment]
> please remove the golangci-lint binary

Removed binary under my most recent commit

**Comment by frederickalcantara** [comment]
Fixed recent conflicts

**Pull request merged**
