### PR TITLE
Slashing precompute: Only apply slashings to state if there are slashings to apply

### PR DESCRIPTION
**Pull request by prestonvanloon**
**What type of PR is this?**

Other

**What does this PR do? Why is it needed?**

As title describes.

**Which issues(s) does this PR fix?**

This reduces memory footprint by reducing unnecessary calls to ApplyToEveryValidator which has an expensive copy of all validators.

**Other notes for review**

### CODE REVIEW

**Review by terencechain — APPROVED** [review]

**Comment by prestonvanloon** [comment]
Please do not merge until Saturday.

**Comment by nisdas** [comment]
@prestonvanloon Might be useful to do a full resync from genesis, to test this out.

**Comment by nisdas** [comment]
Converted it to draft, just to be on the safe side.

**Comment by terencechain** [comment]
superseded by #7587

**Pull request closed without merging**
