### PR TITLE
Revert #9830

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Bug Fix

**What does this PR do? Why is it needed?**

While #9830 was following the consensus spec changes, it also quadrupled bandwidth requirements in certain situations for nodes. Beacon nodes now show significant increases in outbound traffic which was narrowed down to the large increases in `attestion_aggregate_proof` re-propagation. 

**Which issues(s) does this PR fix?**

N.A

**Other notes for review**

### CODE REVIEW

**Review by potuz — APPROVED** [review]

**Review by terencechain — CHANGES_REQUESTED** [review]
#9830 was a spec requirement (https://github.com/ethereum/consensus-specs/issues/2183)  i dont think we should treat this as a simple revert, I think the better course of action will be:

1.) document this in an issue
2.) communicate this with other client teams
3.) get feedbacks
4.) then revert or find better alternatives

**Review by prestonvanloon — APPROVED** [review]
Looks good to me. I have also observed a high increase in upload bandwidth since v2.0.3, but I did not verify that this PR resolves the issue yet.

**Review by terencechain — APPROVED** [review]
Looks like this changes did not make it to other client implementations. I will communicate this back to other client teams and the original issue

**Comment by cgi1** [comment]
I can now verify, that v.2.0.4 solves the high bandwith problem, which has been new in v.2.0.3.

Especially upstream is now back to old levels:

Longer Scale (jump is the update from v.2.0.2 to v.2.0.3):

grafik

After upgrading from v.2.0.3 to v.2.0.4, back close to levels from v.2.0.2:

grafik

**Pull request merged**
