### PR TITLE
Fix example genesis.json

### PR DESCRIPTION
**Pull request by fgimenez**
With the `genesis.json` proposed as an example here https://github.com/prysmaticlabs/geth-sharding#running-a-local-geth-node I'm getting:
```
Fatal: invalid genesis file: invalid character '}' looking for beginning of object key string
```
This PR removes the rogue comma after the only item under `alloc`.

Cheers!

### CODE REVIEW

**Comment by fgimenez** [comment]
@terenc3t thank you! :) Could you please help me with the CLA?

**Comment by rauljordan** [comment]
Hey @fgimenez we changed our CLA bot into one that's a bit more automatic and easier to use. Can you update the branch? It'll listen for a webhook and let you know how to sign it once you do.

**Comment by fgimenez** [comment]
Thanks @rauljordan! should be done now.

**Comment by terenc3t** [comment]
@fgimenez Did you have a chance to sign CLA? there's still a X next to your name
❌ fgimenez

**Comment by fgimenez** [comment]
@terenc3t mmh yesterday I did, and IIRC I had a checkmark beside my name. But you are right, now there's an X. Done again, PTAL.

**Comment by terenc3t** [comment]
Great. Thanks for doing it again!

**Pull request merged**
