### PR TITLE
Hide inactivity scores if 0

### PR DESCRIPTION
**Pull request by terencechain**
No point in logging inactivity stores if it's 0

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Can you give an example of how it looked without this change? I wonder if people were relying on this data to see that their keys had no inactivity penalty

**Comment by terencechain** [comment]
> Can you give an example of how it looked without this change? I wonder if people were relying on this data to see that their keys had no inactivity penalty

Maybe... Happy to leave this PR out for a while to soak in feedback

Screen Shot 2022-08-29 at 9 03 17 AM

**Comment by prestonvanloon** [comment]
I think it's better to leave it than omit if zero. Some log based ingestion may use these for data reporting purposes. 

Unless someone is asking for this to be removed or there is some tangible gain from removing it, then I would leave it there

**Comment by terencechain** [comment]
> I think it's better to leave it than omit if zero. Some log based ingestion may use these for data reporting purposes. 
> 
> 
> 
> Unless someone is asking for this to be removed or there is some tangible gain from removing it, then I would leave it there

Sgtm!

**Pull request closed without merging**
