### PR TITLE
Fixing .bat file issues

### LINKED ISSUE #9260: Prysm.bat is Broken In Usage
# 🐞 Bug Report

### Description

Any users fetching the bat file to use to run the beacon-node or validator will not be able to. Some changes introduced
in #9072 have unfortunately broken the usage of it. 

### Has this worked before in a previous version?

Yes before this PR:
#9072  

## 🔬 Minimal Reproduction

```
prysm.bat beacon-chain
```

## 🔥 Error

```
C:\Prysm>prysm.bat beacon-chain --datadir=C:\prysm --http-web3provider=xxxxx
A subdirectory or file C:\Prysm\dist already exists.
Latest prysm release is v1.4.2.
Using prysm version v1.4.2.
( was unexpected at this time.
C:\Prysm>
```

## 🌍  Your Environment

**Operating System:**

Windows

**What version of Prysm are you running? (Which release)**

v1.4.1 ( This is also observed on v1.4.2).

## Workaround
For any other windows users running into this issue, the workaround is to use the bat script from here:
https://github.com/prysmaticlabs/prysm/blob/fc898d541fdc13faf5be5221833f9a8e904538ee/prysm.bat

This will work the same way as before.

### PR DESCRIPTION
**Pull request by ahadda5**
Many syntactical issues with the .bat 
The main theme was revolving around .bat handling of delayed expansion

**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**
It fixes many syntactical issue with the .bat file. 

- Replacing [] with ""( quotes) if statements in order to protect spaces and other special characters. 
- Using !! vs %% for var with delayed expansion in a block.   See [Delayed Expansion ](https://stackoverflow.com/questions/30282784/variables-are-not-behaving-as-expected)
- As for the issue relating to #9072  , we first check if the file exits without the output(the download) if it is 404 we error otherwise we continue to download (.sh and .ps1 allows in one command). 

**Which issues(s) does this PR fix?**

Fixes #9260

### CODE REVIEW

**Comment by nisdas** [comment]
cc @prestonvanloon , ptal

**Review by prestonvanloon — COMMENTED** [review]
Can you post some screenshot or video that this fixes it? I don't have a windows machine to confirm

**Comment by ahadda5** [comment]
Attached. 
This was tested for beacon-chain, val and client-stats. 
No error was reported due to missing quoted and if stats causing mayhem. 
Files are downloaded if it exists as intended by the original issue. 
No download if 404
download if goodversion

**Comment by nisdas** [comment]
I will give this a try on my windows machine later to confirm that it works on my end too.

**Review by prestonvanloon — APPROVED** [review]

**Pull request merged**
