### PR TITLE
Make QUIC The Default Transport

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

This makes `QUIC` the default transport protocol in prysm and will make every prysm node connect to other nodes via QUIC if supported.

**Which issues(s) does this PR fix?**

N.A

**Other notes for review**

**Acknowledgements**

- [x] I have read [CONTRIBUTING.md](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md).
- [x] I have made an appropriate entry to [CHANGELOG.md](https://github.com/prysmaticlabs/prysm/blob/develop/CHANGELOG.md).
- [x] I have added a description to this PR with sufficient context for reviewers to understand this PR.

### CODE REVIEW

**Comment by prestonvanloon** [comment]
This would be a good time to update quic-go to the latest. It has been a while since we updated it.

**Review by prestonvanloon — APPROVED** [review]
I reviewed libp2p updates and LGTM

**Comment by nalepae** [comment]
> I reviewed libp2p updates and LGTM

(Reviewed them as well!)

**Comment by skylenet** [comment]
Hey folks. Just making a note that this could be breaking someones setup if they used the `13000` port for `-p2p-udp-port` . Maybe it's worth to add a note to the release notes / changelog. This happened to us on our kurtosis setup and I was wondering why it was telling me that port 13000 is already beeing used. Until I noticed that there's this new quic port.

**Comment by nisdas** [comment]
Thanks for bringing this up @skylenet, that is a good point. We will add this to our release notes to flag that this port will be taken up.

**Pull request merged**
