### PR TITLE
fix: update holesky repository layout

### PR DESCRIPTION
**Pull request by barnabasbusa**
Fixes repository layout changes according to: https://github.com/eth-clients/holesky/pull/104

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Thanks @barnabasbusa. This change won't work until we update the reference commit in the WORKSPACE.

We can merge this after https://github.com/eth-clients/holesky/pull/104 merges.

**Comment by james-prysm** [comment]
@barnabasbusa 
```
ERROR: /buildkite/builds/buildkite-2-1/prysmatic-labs/prysm/config/params/BUILD.bazel:41:8: Middleman _middlemen/config_Sparams_Sgo_Udefault_Utest_U_Sgo_Udefault_Utest-runfiles failed: missing input file '@@holesky_testnet//:metadata/config.yaml'
--
  | ERROR: /buildkite/builds/buildkite-2-1/prysmatic-labs/prysm/config/params/BUILD.bazel:41:8: Middleman _middlemen/config_Sparams_Sgo_Udefault_Utest_U_Sgo_Udefault_Utest-runfiles failed: 1 input file(s) do not exist
  ```
  hmm still seems to be broken

**Comment by barnabasbusa** [comment]
The file path should be: `metadata/config.yaml` 

https://github.com/eth-clients/holesky

**Review by prestonvanloon — APPROVED** [review]

**Comment by prestonvanloon** [comment]
Fixed build in 6a046554d3d62d07f1a3223811ab8b95e096ad11

**Pull request merged**
