### PR TITLE
Run StructFieldOrder linter & fix ExecutionPayload findings

### PR DESCRIPTION
**Pull request by jtraglia**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

In #13372 I mentioned wanting to make a simple static analyzer for enforcing struct field order. Well this PR adds this to the CI linter checks. Currently, it only looks at `ExecutionPayload*` structs. In the future, after all the findings have been fixed (in separate PRs) we can remove the `-i` (include) arguments.

* https://github.com/prysmaticlabs/prysm/pull/13372

### CODE REVIEW

**Review by terencechain — DISMISSED** [review]

**Comment by rkapka** [comment]
@jtraglia can you please resolve conflicts? Thanks!

**Review by terencechain — APPROVED** [review]
Thank you for doing this!

**Comment by jtraglia** [comment]
Hey @terencechain, buildkite is blocked/stalled for some reason. Can we kick it?

**Comment by prestonvanloon** [comment]
@jtraglia sorry about the delay on this. Could you fix conflicts and I'll make sure this gets pushed through? Thanks

**Comment by jtraglia** [comment]
> @jtraglia sorry about the delay on this. Could you fix conflicts and I'll make sure this gets pushed through? Thanks

No problem, yeah I'll fix the conflict tomorrow.

**Comment by jtraglia** [comment]
This isn't going to get merged.

**Pull request closed without merging**
