### PR TITLE
Fix Goimports and DeepSource

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Cleanup

**What does this PR do? Why is it needed?**

Our CI check was broken in this branch by a recent merge, this PR remedies it by fixing all imports. This PR also fixes all deep source reported issues

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

### CODE REVIEW

**Comment by prestonvanloon** [comment]
> Go / Check (pull_request) Failing after 49s

Looks like some files not imported according to the linter

**Comment by nisdas** [comment]
> err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

@prestonvanloon Seems like a bug with the linter, it fails to lint a few files with the above error and then complains.

**Comment by prestonvanloon** [comment]
```
All following has imports not properly ordered
beacon-chain/core/blocks/attestation_test.go
beacon-chain/rpc/prysm/v1alpha1/beacon/attestations_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
```

**Comment by prestonvanloon** [comment]
Not sure what the underlying issue is here, but we should fix the github action before merging this. Otherwise it will just be red for everyone and be ignored.

**Review by prestonvanloon — APPROVED** [review]

**Pull request merged**
