### PR TITLE
Remove StreamDuties

### PR DESCRIPTION
**Pull request by PatriceVignola**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

`StreamDuties` doesn't seem to be used by anything anymore. Instead of adding an implementation for the REST API validator that may never get used for anything, we can just remove it. I ran the endtoend tests and everything seems to pass.

### CODE REVIEW

**Review by terencechain — CHANGES_REQUESTED** [review]
I support this change but this is a breaking change and we can't merge this until a major release. We should wait for this type of deprecation until closer to V4

**Comment by PatriceVignola** [comment]
> I support this change but this is a breaking change and we can't merge this until a major release. We should wait for this type of deprecation until closer to V4

That's what I was suspecting, but I couldn't figure out what it was breaking since there doesn't seem to be any call to `StreamDuties` in the repo. Is anything else depending on this, or calling this function by reflection?

**Comment by terencechain** [comment]
> 

Other applications (outside of Prysm) may depend on it

**Comment by terencechain** [comment]
Didnt have to close this. We can merge this as it gets closer to V4. I think early march would be good

**Comment by PatriceVignola** [comment]
> Didnt have to close this. We can merge this as it gets closer to V4. I think early march would be good

Sounds good, I'll reopen it early March! Thanks!

**Pull request closed without merging**
