### PR TITLE
Add field roots for beacon state v3

### PR DESCRIPTION
**Pull request by terencechain**
Part of implementing beacon state v3 (version: Merge) pkg. This PR adds all field roots related functionalities. These files are essentially duplicated from v2

As a reviewer, please cross check they are correctly duplicated from v2

### CODE REVIEW

**Review by nisdas — DISMISSED** [review]

**Review by nisdas — APPROVED** [review]

**Comment by terencechain** [comment]
Regarding `  Error: `computeFieldRoots` is unused (deadcode)` from golint, it will be addressed in the next pr

**Comment by nisdas** [comment]
@terencechain you will need to add an exception as we cant merge without gocheck passing.

**Comment by terencechain** [comment]
> @terencechain you will need to add an exception as we cant merge without gocheck passing.

ah, forgot it's required, ready again

**Comment by nisdas** [comment]
Can you add in an exception for deadcode instead of the whole package for that particular struct ?
```
//nolint:deadcode
```

**Review by nisdas — APPROVED** [review]

**Comment by terencechain** [comment]
thanks @nisdas !

**Pull request merged**
