### PR TITLE
Integrate Blox's remote Vault HTTP keymanager

### PR DESCRIPTION
**Pull request by roman-blox**
Added the integration with Blox's Vault plugin. Basically, there is the remote HTTP key manager that knows how to communicate with Vault plugin running on a remote host through HTTP requests.

### CODE REVIEW

**Comment by rauljordan** [comment]
Hi @roman-blox thanks for the submission! Our bad that we don't have clear enough information on how to add new keymanagers, however, the code you added was to the deprecated, v1 accounts management. For example, the `--keymanager` flag is deprecated, but not marked as such yet because we haven't removed the code from the codebase. Adding a new keymanager isn't easy, unfortunately, but a place to start would be to conform to this interface:
```go
// IKeymanager defines a general keymanager-v2 interface for Prysm wallets.
type IKeymanager interface {
	// FetchValidatingKeys fetches the list of public keys that should be used to validate with.
	FetchValidatingPublicKeys(ctx context.Context) ([][48]byte, error)
	// Sign signs a message using a validator key.
	Sign(context.Context, *validatorpb.SignRequest) (bls.Signature, error)
}
```
defined [here](https://github.com/prysmaticlabs/prysm/blob/master/validator/keymanager/v2/types.go). Then, you can add it to the `InitializeKeymanager` function here: https://github.com/prysmaticlabs/prysm/blob/master/validator/accounts/v2/wallet.go#L172. Sorry this isn't as straightforward as the v1 and v2 code is still convoluted with each other in some places, but we will be working on phasing it out soon.

**Comment by roman-blox** [comment]
@rauljordan thanks for the feedback! We've updated our keymanager according to your keymanager v2 interface. Could you please review one more time?

**Comment by prestonvanloon** [comment]
Looking at bazel issues. This is the first PR that includes a third party library which depends on Prysm code.

**Comment by prestonvanloon** [comment]
Sorry for the delay, this is partially blocked by #7202. I'm prioritizing this to land in the next release alpha.28. Thanks

**Comment by alonmuroch** [comment]
@prestonvanloon the stale bot is about to close it..

**Comment by prestonvanloon** [comment]
Update on this, still blocked. I hoped it would be fixed in a recent version of rules_go and gazelle, but the issue persists. I've filed https://github.com/bazelbuild/bazel-gazelle/issues/953 and we'll see what the best path forward is there.

**Comment by alonmuroch** [comment]
@prestonvanloon maybe we should re-think how we want to integrate the key manager? We might be over-engineering it..

**Pull request closed without merging**
