### PR TITLE
Adding ability to override directory permissions for db backup

### LINKED ISSUE #8504: Offer an option to ignore the file permissions check when calling the DB backup webhook
As a consequence of putting in place a backup and recovery plan, I recently adopted the database backup webhook that is recommended by the team. However, Prysm is forcing me to use 0700 on `--db-backup-output-dir`, which my backup daemon can't access. I'd like to ask for a user override, which can disable the file permission check.

### PR DESCRIPTION
**Pull request by d00medman**
**What type of PR is this?**
Feature

**What does this PR do? Why is it needed?**
Creates a command line argument which allows the db backup directory to override existing file permissions on the directory

**Which issues(s) does this PR fix?**

Fixes #8504 

**Other notes for review**
First PR, tested locally and it worked; added test cases for the file handler; happy to add more if needed. 

 It does not feel great to make such a broad change for such a seemingly small gain. Main issue is that doing this requires either altering mkdirall (which I opted for) or spinning up a new mkdir method for backups with this ability.

### CODE REVIEW

**Comment by nisdas** [comment]
This change would be pretty invasive to add in, as it adds in a new flag specifically just to add in a different set of permissions. In the original issue, there might be a better way of instantiating this rather than adding in an override everywhere.

**Comment by d00medman** [comment]
@nisdas I was thinking that myself. I think the less invasive way of doing this would be to swap out mkdirall for a method used exclusively by backup (HandleBackupDir, which would look almost exactly like mkdirall, but with the additional chmod).

If a command line flag is not the way to go, how would we activate this? One option would be a url param for the backup endpoint; the other would be to always perform the permission override for the backup directory; my guess is the former would be preferable.

**Comment by d00medman** [comment]
Ok, I've reduced the footprint by having the backup use a distinct method for file handling. Only outstanding question is "should this override to always be on for backup creation?" If this should be user-enabled, but not via a command line flag, the only other way I see this being viable is with a url parameter (something like `/db/backup?override`). Having the backup always override to the correct permissions would be cleaner, but the issue's OP requested a user enabled override. I'm fine either way, please advise which makes more sense.

**Comment by nisdas** [comment]
@d00medman 

Hey sorry for taking a long time to reply on this, I am bit skeptical on introducing a new flag for this. Given that this a minor user issue, having a flag specifically for overriding permissions seems excessive(since this is a backup). Maybe specifying this via a url parameter would be a better approach here as you have mentioned.

**Review by rauljordan — APPROVED** [review]

**Pull request merged**
