### PR TITLE
Fix bugs in `/eth/v1/beacon/blinded_blocks`

### PR DESCRIPTION
**Pull request by rkapka**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

I found a few bugs in the implementation of `/eth/v1/beacon/blinded_blocks` endpoint when testing on Kiln.

### CODE REVIEW

**Review by terencechain — COMMENTED** [review]
How about some unit tests?

**Comment by rkapka** [comment]
What kind of unit tests do you have in mind? These changes are basically struct definitions.

**Comment by rauljordan** [comment]
What bug does this fix @rkapka ? I think Terence is referring to the change from hex to uint256 and whether or not that will fix the issue you observed. If we can add a test that would check if this works as expected that would be nice

**Comment by rkapka** [comment]
I will think about a test case.

> What bug does this fix @rkapka ?

I found out that this endpoint does not work on Kiln.

**Review by terencechain — APPROVED** [review]
I think this is fine as it is, I was being extra prudent.
I suppose one way to validate is to check the returns `ExecutionPayloadHeader` has the correct JSON name and `BaseFeePerGas` is in `uint256` not `hex`, will leave that up to you!

**Pull request merged**
