### PR TITLE
Update fastssz

### PR DESCRIPTION
**Pull request by terencechain**
**What type of PR is this?**

> Feature

**What does this PR do? Why is it needed?**

Update to latest fastssz which will sort files by path before generating `ssz.go`. Yay for consistent result. Thanks @pinglamb for the work on the `fastssz` side

**Which issues(s) does this PR fix?**

N/A

**Other notes for review**

Ethereumapi review: https://github.com/prysmaticlabs/ethereumapis/pull/217

### CODE REVIEW

**Review by prestonvanloon — CHANGES_REQUESTED** [review]
Please regenerate all of the ssz files. 

```
./scripts/update-go-ssz.sh
```

**Comment by terencechain** [comment]
> Please regenerate all of the ssz files.
> 
> ```
> ./scripts/update-go-ssz.sh
> ```

We did and there's no diff. This PR is more on the preventive side so the next person to add bunch of fields to `types.proto` and the person wont reordering issues. (e.g. prysmaticlabs/ethereumapis#217)

**Comment by prestonvanloon** [comment]
I dont understand, if fssz reorders objects now, why isn't there a diff?

**Comment by pinglamb** [comment]
@prestonvanloon FYI, we have 2 `sszgen` calls in the project. The first one is in `fuzz` and there is only one file input (`inputs.go`) so the result is the same. The second one is in `proto/beacon/p2p/v1` which involves 2 files (`messages.pb.go` and `types.pb.go`), the existing `generated.ssz.go` already in the right order, so the result is also the same.

**Pull request merged**
