### PR TITLE
Added flag for specifying header request limit

### LINKED ISSUE #7827: Unable to process past logs query returned more than 10000 results
# 🐞 Bug Report

### Description

When running a beacon node on pyrmont with an infura endpoint, the powchain receives this error.

```
ERROR powchain: Unable to process past logs query returned more than 10000 results
```

### Has this worked before in a previous version?

Yes, in other testnets. Although other testnets have not enjoyed such rapid deposits up to 100k.

## 🔬 Minimal Reproduction

```
beacon-chain --pyrmont --clear-db --http-web3provider=https://goerli.infura.io/...
```

## 🔥 Error

<pre><code>
[2020-11-16 11:42:03]  INFO powchain: Connected to eth1 proof-of-work chain endpoint=https://goerli.infura.io/v3/REDACTED
[2020-11-16 11:42:03] ERROR powchain: Unable to process past logs query returned more than 10000 results
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
linux amd64
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-beta.3
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

### PR DESCRIPTION
**Pull request by pinglamb**
**What type of PR is this?**

> Feature

**What does this PR do? Why is it needed?**

Added `-eth1-header-req-limit` flag to beacon-node to control the maximum number of headers to fetch per query.
So user can set a lower limit (e.g. 150) when they use infura to prevent `Unable to process past logs query returned more than 10000 results`

**Which issues(s) does this PR fix?**

Fixes #7827 

**Other notes for review**

Suggestion on naming of the flag is welcome.

### CODE REVIEW

**Comment by pinglamb** [comment]
The start command with be like:

```
beacon-chain --pyrmont --clear-db --http-web3provider=https://goerli.infura.io/... --eth1-header-req-limit=150
```

**Review by prestonvanloon — APPROVED** [review]
LGTM

**Comment by nisdas** [comment]
I am not sure if we really need this, we have only ever had this issue in pyrmont because there were 100,000 deposits packed into 1000 blocks. In the mainnet or future testnets this will very unlikely be an issue. I am hesitant to add a new flag that will only be used for pyrmont.

**Comment by pinglamb** [comment]
How do users deal with this error in case it happens? The node will probably just stuck there unless users switch the web3 endpoint.

Agree that this option might be a bit too technical. Can the beacon node has a way to recover itself from this in case it happens? Like retry with a lower header count?

**Comment by nisdas** [comment]
> Agree that this option might be a bit too technical. Can the beacon node has a way to recover itself from this in case it happens? Like retry with a lower header count?

This would be a better solution in my opinion, rather than add another temporary flag, we have a more graceful retry.

**Comment by prestonvanloon** [comment]
@nisdas can we accept this to unblock #7827 and revisit in a follow up? 
A flag might not be ideal but users are getting blocked by this daily.

**Review by nisdas — APPROVED** [review]

**Comment by nisdas** [comment]
In the interest of unblocking users in #7827, I will approve it for now, although I would have preferred not too introduce what most likely will be a very temporary flag. We can revisit having better retries later.

**Pull request merged**
