### PR TITLE
State size metric

### PR DESCRIPTION
**Pull request by prestonvanloon**

### CODE REVIEW

**Comment by rauljordan** [comment]
This only logs the size of the state upon init, but not on subsequent times. Can we also monitor the updating of the state?

**Comment by rauljordan** [comment]
Oh sorry just saw this is a WIP

**Comment by prestonvanloon** [comment]
This updates on SaveState which is actually almost never called

**Comment by terenc3t** [comment]
@prestonvanloon is this ready?

**Comment by prestonvanloon** [comment]
@terenc3t no, the state is saved in multiple places. We would need some refactoring to capture state updates in a single method. 

This is a low priority for me so I haven't addressed it

**Comment by prestonvanloon** [comment]
The multiple saveState entrypoints have been consolidated to one. So this is good to go!

**Pull request merged**
