### PR TITLE
Dont return if proposer boost roots are missing

### PR DESCRIPTION
**Pull request by potuz**
In the event that the proposer boost roots are missing, simply log an error and continue.

### CODE REVIEW

**Review by terencechain — COMMENTED** [review]
Do you want to add some unit tests?

**Comment by potuz** [comment]
> Do you want to add some unit tests?

Spectests won't pass without this fix (the change in spectest is to run with doubly-linked-tree)

**Comment by terencechain** [comment]
Sure. Although it'd be nice not to depend on spec test. I'll be happy to add unit tests for this after it's merged

**Comment by potuz** [comment]
> Sure. Although it'd be nice not to depend on spec test. I'll be happy to add unit tests for this after it's merged
I think I can add a unit test, it's a little bit of a mess but it shouldn't be too hard.

**Review by terencechain — APPROVED** [review]

**Pull request merged**
