### PR TITLE
Invert init-sync-batch-save-blocks flag for v0.11

### LINKED ISSUE #5281: invert "--initial-sync-batch-save-blocks" flag
2x speed up for initial syncing would be great to have as default

### PR DESCRIPTION
**Pull request by terencechain**
This fixes #5281

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Any reason this can't go into master?

**Comment by terencechain** [comment]
> Any reason this can't go into master?

It can, I have been throughly testing this on master with our cluster. But just to be extra safe, I wanna to test this with v0.11.1 dev cluster starting day 1 (then goto master), and the diff is tiny enough to bundle with v0.11.1

I don't feel strongly about this decision though, if people think it should be part of master then im down 👍

**Comment by prestonvanloon** [comment]
My thinking is that we incrementally release any features into master that are not breaking changes. V0.11 branch already has a lot of features and changes, adding more may make it more difficult to debug. 

If this is already running in master, then there is no risk to merge to master and if there is some issue, we will learn about it sooner.

**Comment by rauljordan** [comment]
+1 @terencechain can we cherry pick and merge against master?

**Comment by terencechain** [comment]
Sounds good. Changed based to master

**Pull request merged**
