### PR TITLE
Optimize ETH1 Data Vote

### PR DESCRIPTION
**Pull request by nisdas**
This optimizes the data vote function in the beacon server, by reducing the number of calls to the ETH 1.0 chain for either retrieving the block or checking that it exists. Also cleans up a lot of redundant rpc calls to the main chain. With the current optimizations the method's time complexity is O(N)

### CODE REVIEW

**Comment by terenc3t** [comment]
would be nice to see some benchmark tests for the before and after changes

**Comment by nisdas** [comment]
@terenc3t This is before 
```
goos: linux
goarch: amd64
pkg: github.com/prysmaticlabs/prysm/beacon-chain/rpc
Benchmark_Eth1Data-8   	      10	 201510985 ns/op
PASS
```

and after 
```
goos: linux
goarch: amd64
pkg: github.com/prysmaticlabs/prysm/beacon-chain/rpc
Benchmark_Eth1Data-8   	      10	 102855368 ns/op
PASS
```
It is twice as fast after, also the pow chain in this is mocked, so including that in runtime it will be even faster since we have cutdown the unecessary calls

**Comment by prestonvanloon** [comment]
Can you elaborate on the optimisation? This looks like it went from `2*n` to `n`. How is it a O(1) operation?

**Comment by nisdas** [comment]
@prestonvanloon It would be when the size of the number of votes is zero. This would only happen once , and that would be at genesis. Maybe stating O(1) isnt very relevant here, I will change the PR description.

**Comment by prestonvanloon** [comment]
#1430 related

**Pull request merged**
