### PR TITLE
cmd/beacon-chain: add jwtcommands

### PR DESCRIPTION
**Pull request by jsvisa**
Signed-off-by: Delweng <delweng@gmail.com>

**What type of PR is this?**

Feature: add jwt subcommands into the beacon-chain main process

**What does this PR do? Why is it needed?**

Documents from https://docs.prylabs.network/docs/install/install-with-script#step-3-generate-secret said:

> This will download the Prysm client and make it executable. Use the following command to create your secret JWT token:
> ./prysm.sh beacon-chain jwt generate-jwt-secret

But actually when I'm run this command, raise the exception as below:

```
$ ./prysm.sh beacon-chain jwt generate-jwt-secret
Latest Prysm version is v2.1.2.
Beacon chain is up to date.
Verifying binary integrity.
beacon-chain-v2.1.2-linux-amd64: OK
gpg: Signature made Mon 16 May 2022 07:13:15 PM UTC using RSA key ID F1A5036E
gpg: Good signature from "Preston Van Loon <preston@prysmaticlabs.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
Verified /md0/ropsten/consensus/prysm/dist/beacon-chain-v2.1.2-linux-amd64 has been signed by Prysmatic Labs.
Starting Prysm beacon-chain jwt generate-jwt-secret
[2022-06-22 02:35:20] ERROR main: unrecognized argument: jwt
```

after some google and code review, found the [cmd/beacon-chain/jwt](cmd/beacon-chain/jwt) package was not included in the main beacon-chain process.

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

### CODE REVIEW

**Review by symbolpunk — DISMISSED** [review]

**Comment by symbolpunk** [comment]
Thank you so much @jsvisa 🙏

**Comment by nisdas** [comment]
@jsvisa You need to run gazelle on this so as to add in the correct dep to the build file.

**Comment by jsvisa** [comment]
> @jsvisa You need to run gazelle on this so as to add in the correct dep to the build file. 

Could you please tell me which command to run this?

**Comment by nisdas** [comment]
`bazel run //:gazelle -- fix`

**Comment by prestonvanloon** [comment]
I ran gazelle. Thanks!

**Review by prestonvanloon — APPROVED** [review]

**Pull request merged**
