### PR TITLE
Use a client side rate limit to reduce chance of getting banned

### LINKED ISSUE #4588: Rapid drop off peers
image

`bazel run //beacon-chain -- --save-deposit-data --min-sync-peers 5 --enable-ssz-cache --datadir=$HOME/prysm`

### LINKED ISSUE #4621: Beacon Chain peers disconnect in block 35848 - using bazel
I did it already 3 times. The same block ... all peers disconnect. 

[2020-01-22 22:38:25]  INFO initial-sync: Processing block 35848/92892 - estimated time remaining 105h38m13s blocksPerSecond=0.1 peers=5/13
[2020-01-22 22:38:30]  INFO p2p: Peer disconnected active=12 peer=16Uiu2HAm7V6p2HgCx3JhmxRBuiXmFL6QTjbHssUiUs7cXUe18Bkd
[2020-01-22 22:38:30]  INFO p2p: Peer disconnected active=11 peer=16Uiu2HAmRMqPe1nR1yAwUEpBKzUh8ABHzcMBSRnnK1z4fkuARu8e
[2020-01-22 22:38:30]  INFO p2p: Peer disconnected active=10 peer=16Uiu2HAmLpabFfbMpMyZhqEevu2hCfCuiRyc2gSWaRUVP9ozSA8j
[2020-01-22 22:38:30]  INFO p2p: Peer disconnected active=9 peer=16Uiu2HAm12JGMpCDPnp3MzoJ2qAHkqESBSM9sU7Pf2ukeiQZ7KnF
[2020-01-22 22:38:30]  INFO p2p: Peer disconnected active=8 peer=16Uiu2HAkz1t6hf1xcyknqASiGxWwQHqb6griqnMu5Wt2MC6yhhK9
[2020-01-22 22:38:35] ERROR initial-sync: Round robing sync request failed error=no peers left to request blocks
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
[2020-01-22 22:38:35]  INFO p2p: Peer disconnected active=7 peer=16Uiu2HAmEJB957TtRMKgAYYQjDomDbLt1hLJbk2jVqNYjHrmfJys
[2020-01-22 22:38:36]  INFO p2p: Peer disconnected active=6 peer=16Uiu2HAmCVsokwnprH7QJyCMh9FuSVnQwV9a4hQ5RjzmZnbNyuYv
[2020-01-22 22:38:42] ERROR initial-sync: Round robing sync request failed error=no peers left to request blocks
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
[2020-01-22 22:38:43]  INFO p2p: Peer disconnected active=5 peer=16Uiu2HAm31CrTnSqozW2o1ovsmZ6wxRXioYBpRSLvQGyq8QtfWRP
[2020-01-22 22:38:43]  INFO p2p: Peer disconnected active=4 peer=16Uiu2HAmAsyW714qpiYz9dNEoDyLa29SuzXwU4sY3fQrRtUxN1bT
[2020-01-22 22:38:43] ERROR initial-sync: Round robing sync request failed error=no peers left to request blocks
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
[2020-01-22 22:38:45] ERROR initial-sync: Round robing sync request failed error=no peers left to request blocks
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
[2020-01-22 22:38:45]  INFO p2p: Peer disconnected active=3 peer=16Uiu2HAmJNZnTxJ2U3aHr8gzLb4xZnHmVXUPTNkQQMuFcP9RPg11
[2020-01-22 22:38:46]  INFO p2p: Peer disconnected active=2 peer=16Uiu2HAm7XcCk3Z93SftzYVmGJtcJ4c2QVnokroJae5dgk3B23EM
[2020-01-22 22:38:46] ERROR initial-sync: Round robing sync request failed error=no peers left to request blocks
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
[2020-01-22 22:38:53] ERROR initial-sync: Round robing sync request failed error=no peers left to request blocks
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
[2020-01-22 22:38:53] ERROR initial-sync: Round robing sync request failed error=no peers left to request blocks
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
[2020-01-22 22:39:01] ERROR initial-sync: Round robing sync request failed error=no peers left to request blocks
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:140
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
[2020-01-22 22:39:01]  WARN initial-sync: No peers; waiting for reconnect
[2020-01-22 22:39:01]  INFO p2p: Peer disconnected active=1 peer=16Uiu2HAm7ruW6N9xyeJMqZwUX4wUfvMUhKRgGQadLYxaPwubVPr5
[2020-01-22 22:39:07]  WARN initial-sync: No peers; waiting for reconnect
[2020-01-22 22:39:13]  WARN initial-sync: No peers; waiting for reconnect
[2020-01-22 22:39:19]  WARN initial-sync: No peers; waiting for reconnect

### PR DESCRIPTION
**Pull request by prestonvanloon**
Resolves #4588
Resolves #4621 

Maybe helps #4631 

Part of the issue is that when there are large ranges of skip slots, we might be asking for the peer for many blocks very quickly. Even when there are no blocks present in that range, the server increments that rate limit by the request count. Adding this client side rate limit should reduce the risk of bombing peers with requests.

### CODE REVIEW

**Comment by mcdee** [comment]
> Even when there are no blocks present in that range, the server increments that rate limit by the request count

Is this valid for the server to do?  It it a similar magnitude of work to check for empty slots as it is to serve those with blocks in it?  Or should the rate limiting be done on actual blocks served?

**Comment by prestonvanloon** [comment]
@mcdee I think it's valid. The client is knowingly requesting a high rate of blocks/slots per second, although they do not know if there are actually blocks in those slots.

**Comment by mcdee** [comment]
True, but the only reason it is requesting more blocks soon after the last request is because there were few-to-none blocks returned last time around.

Given this situation only really occurs when we have finality issues, I'm wondering if being more lenient on the server side here would help the network get back on its feet if such a thing happened in production.  I'm not suggesting the server hurt itself in the process, but if it is cheap and easy to return 0 blocks I'd be inclined to reflect that in the rate limiting.

**Comment by prestonvanloon** [comment]
Supporting that type of rate limiting will require some database changes to determine how many blocks are present in a given range without unmarshalling them. As it is now, we check the rate limit, if OK then we fetch the request range of blocks. 

We could enhance this process to be:
- Secure peer ID based mutex
- Fetch up to `min(remainingLimit, req.Count)` blocks from db in the requested range
- Increment limit by the amount of blocks returned
- Return blocks

For now it's simpler on the server side to check if the requested count exceeds the limit and exit early without a database read. Given that the limit allows bursts of 320 blocks per second, I think this is a reasonable response from any given peer.

**Pull request merged**
