### PR TITLE
Refactor validator accounts delete to remove cli context dependency

### PR DESCRIPTION
**Pull request by michaelneuder**
**What type of PR is this?**
Refactor/code health

**What does this PR do? Why is it needed?**
This PR addresses the account list code and refactors it as part of https://github.com/prysmaticlabs/prysm/issues/9883. It follows up on https://github.com/prysmaticlabs/prysm/pull/10554, which does a similar migration for the accounts list functionality. 

For delete it gets a bit more involved. But I am curious to hear what you think! Here is a high level of whats going on:

1. `cmd/validator/accounts/delete.go`. This is a new file that parses the CLI flags and constructs the CLI manager with the appropriate options. On the CLI manager, it simply calls the `Delete` method with the `context.Context` type (no longer a need for the `cli.Context`.
2. `cmd/validator/accounts/delete_test.go`. This is the new location of the test that was previously `validator/accounts/accounts_delete_test.go`. As written, that test is built for the CLI context interface, so if we are moving the logic for handling that to the `cmd/validator/accounts` directory, it makes sense to also move the test there. I had to copy a few helper test functions into this file to get it to compile. So for now there is a bit of code duplication. I expect this to level out as we start migrating the other CLI tests into this directory. 
3. `cmd/validator/accounts/wallet_utils.go`. This is a new file for shared functionality between list and delete (right now just has `walletWithKeymanager`).
4. `validator/accounts/accounts_delete.go`. This is where we see the benefit of this refactor. We chop out all the CLI parsing stuff from the `DeleteAccountCli` function, and make it a `Delete` method on the AccountsCLIManager pointer receiver.
5. `validator/accounts/accounts_helper.go`. I made a minor change here to separate the `filterPublicKeysFromUserInput` into two pieces for readability. I also made this function exported because we now use it in the `cmd/validator/accounts` package. Since it is still in use for files in the `validator/accounts` package, I thought it would be easier to export it for now, and then once it is  only used in the `cmd/validator/accounts` dir, we can make it non-exported again.
6. `validator/accounts/cli_manager.go` and `validator/accounts/cli_options.go`. I added a few new options that the delete function requires. As we continue refactoring we can tell which of these options are actually needed. If they are only used by a single method on the AccountsCLIManager type, then we can just pass them as arguments for that method.

LMK what you think! This one was certainly a bit more involved than the List functionality, but I still think the separation of concerns (decouple CLI parsing from the actual functions in the validator/accounts package) is a nice improvement and the readability + maintainability of `validator/accounts/accounts_delete.go` is much improved. 

**Which issues(s) does this PR fix?**

This is part of the keymanager refactor defined in https://github.com/prysmaticlabs/prysm/issues/9883.
It is also described in https://github.com/prysmaticlabs/prysm/issues/10339.

### CODE REVIEW

**Review by rauljordan — APPROVED** [review]
This is really clean! I could not find anything wrong with this PR after two reviews

**Comment by rauljordan** [comment]
It just needs to run `bazel run //:gazelle -- fix` @michaelneuder

**Comment by michaelneuder** [comment]
> It just needs to run `bazel run //:gazelle -- fix` @michaelneuder

done!

**Comment by michaelneuder** [comment]
> This is really clean! I could not find anything wrong with this PR after two reviews

sweet! thanks! glad the decisions made sense. :-)

**Review by rauljordan — APPROVED** [review]

**Pull request merged**
