### PR TITLE
Add Pyrmont config

### PR DESCRIPTION
**Pull request by terencechain**
This PR adds Pyrmont config

https://github.com/protolambda/pyrmont

### CODE REVIEW

**Review by prestonvanloon — APPROVED** [review]

**Review by prestonvanloon — CHANGES_REQUESTED** [review]
Genesis time is supposed to be 1605700800. 

https://github.com/protolambda/pyrmont/blob/54d7f9f563b8d89c8bfc70cb62f9032ba6bc2880/config.yaml#L20

**Comment by protolambda** [comment]
My bad, I messed up the readme and left the old toledo genesis time in there. The config is correct

**Comment by protolambda** [comment]
Does Prysm check the chain ID / network ID that the eth1 RPC supports? May be a good feature to warn the user if they are still on goerli, while they should soon be on mainnet!

**Comment by terencechain** [comment]
> Does Prysm check the chain ID / network ID that the eth1 RPC supports? Maybe a good feature to warn the user if they are still on goerli, while they should soon be on mainnet!

We do check. It's here:
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/powchain/service.go#L405

**Review by prestonvanloon — APPROVED** [review]

**Pull request merged**
