### PR TITLE
Add ssz marshal and unmarshal for most data structures

### PR DESCRIPTION
**Pull request by prestonvanloon**
Changes:

- Patch go-ssz to check if the struct meets new ssz interface, use that if appliciable.
- Update Ferran's ssz to an experimental branch that allows specifying imports
- Update tool usage of ferran's ssz to support imports
- Add ssz targets for common data structures (at least those used in beacon-fuzz)

### CODE REVIEW

**Comment by rauljordan** [comment]
A good amount of test targets fail @prestonvanloon

**Comment by prestonvanloon** [comment]
blocked by https://github.com/ferranbt/fastssz/issues/1

**Comment by prestonvanloon** [comment]
Still seems a bit of work to do. I fixed the blocking issue in https://github.com/ferranbt/fastssz/pull/2, but trying these changes locally still has issues. 

Some of the issues are round trip marshal / unmarshal in initial sync and other places. I'll continue investigation tomorrow.

**Comment by prestonvanloon** [comment]
Currently blocked by https://github.com/ferranbt/fastssz/issues/4

**Comment by prestonvanloon** [comment]
Should be unblocked now that we are referencing a commit that fixes ferranbt/fastssz#4. This branch hasn't merged to master yet though

**Pull request merged**
