### PR TITLE
WIP // for phase2 // create wasm contract "Sender"

### PR DESCRIPTION
**Pull request by skillful-alex**
In this pull request, I show a possible contract to start developing a web assembler.

**Discussion** - I think we can’t use wasmerio, because he will not allow gas to be calculated. I am ready to create own implementation of a wasm machine that will be slow but flexible (embed gas calculation instructions in wasm binary code or call go on each wasm instruction). Try this way?

### CODE REVIEW

**Comment by skillful-alex** [comment]
addition:
default go compiler 1.2MB (wasm)
tinygo compiler 8.9 KB (wasm)
solidity compile 423 bytes (evm bytecode)   :1st_place_medal:

**Comment by skillful-alex** [comment]
One more addition: If we inject gas calculation instructions in wasm binary code (change the wasm code), then we can use wasmerio. It is the way to speed but smells like hacking.

**Comment by rauljordan** [comment]
Hey @skillful-alex this looks great - could you resolve the conflict that exists and fix up the lint failure so we can merge this in?

**Comment by rauljordan** [comment]
Hey @skillful-alex just a quick follow-up on this

**Comment by skillful-alex** [comment]
ok. Please give me time until Monday.

**Comment by skillful-alex** [comment]
due to a change in PR logic was created new PR: https://github.com/prysmaticlabs/prysm/pull/4229

**Pull request closed without merging**
