### PR TITLE
Prevent parent block with same slot

### PR DESCRIPTION
**Pull request by terencechain**
Note: Blocked by new spec test

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Can you confirm all of the changes from https://github.com/ethereum/eth2.0-specs/pull/1818 are present in this PR? 

v0.11.3 was release in eth2 specs but spec tests have not been updated yet: https://github.com/ethereum/eth2.0-spec-tests

**Comment by terencechain** [comment]
> Can you confirm all of the changes from [ethereum/eth2.0-specs#1818](https://github.com/ethereum/eth2.0-specs/pull/1818) are present in this PR?

confirmed

**Comment by prestonvanloon** [comment]
Spec tests are out https://github.com/ethereum/eth2.0-spec-tests/releases/tag/v0.11.3

**Comment by prestonvanloon** [comment]
Could you also bump the badge in the readme? I think this PR brings us compliant to 0.11.3.

**Pull request merged**
