### PR TITLE
Release State References

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Feature Addition

**What does this PR do? Why is it needed?**

- [x] Manually releases state references instead of using the GC to keep track of it. This allows for less redundant 
copies of large fields to be carried out.
- [x] Add Unit Tests for this Feature.
- [x] Add in a feature flag to gate this in.

**Which issues(s) does this PR fix?**

N.A

**Other notes for review**

### CODE REVIEW

**Comment by rauljordan** [comment]
Is this still needed @nisdas if we now have the immutable validator code?

**Comment by nisdas** [comment]
Yes, this will be a big improvement for memory usage in general for our node. It allows us to sidestep the finalizer when de-referencing beacon states. Its complementary to our immutable validator code.

**Comment by prestonvanloon** [comment]
What's the status on this PR?

**Comment by nisdas** [comment]
@prestonvanloon Closing it for now, there has been limited observed benefit from it.

**Pull request closed without merging**
