### PR TITLE
Add sent block time metric

### PR DESCRIPTION
**Pull request by terencechain**
**What type of PR is this?**
> Feature

**What does this PR do? Why is it needed?**
Add sent block time metric to monitor proposer <-> BN operation

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Please be cautious about adding too many histograms. They create additional / significant data carnality and we already have the above information through tracing spans.

**Comment by terencechain** [comment]
> Please be cautious about adding too many histograms. They create additional / significant data carnality and we already have the above information through tracing spans.

I think this is acceptable. This only gets triggered when a proposer proposes a block which is rare event. I have been getting asked by Proto and Danny for how long it takes for a proposer to propose a block, it's good to apply this metric to every node

**Comment by prestonvanloon** [comment]
OK. Can we draw the line here? If we satisfy every "how long does X" take with a histogram then carnality will be very high. This is why we have tracing to answer those questions.

**Comment by prestonvanloon** [comment]
s/carnality/cardinality/g

**Comment by terencechain** [comment]
> OK. Can we draw the line here? If we satisfy every "how long does X" take with a histogram then carnality will be very high. This is why we have tracing to answer those questions.

Where we drew the line is based on the frequency and importance
Ex: we don't do this for attestations because 
1.) There's more attestations than block. `Once per slot` versus `Once / validator_count per slot`
2.) Delayed attestation isn't as bad as delayed block in terms of network health
3.) Block carries more profitability than attestation

**Comment by terencechain** [comment]
With that said, I'm also happy to take this out when we are fully satisfy with p2p and netwok related performance.   Sometime during multi client and before mainent, we should sweep through all the metrics and remove the ones that don't serve much value

**Comment by prestonvanloon** [comment]
> With that said, I'm also happy to take this out when we are fully satisfy with p2p and netwok related performance. Sometime during multi client and before mainnet, we should sweep through all the metrics and remove the ones that don't serve much value

Yes for sure, many of these metrics are not consistent with naming or tracked deprecated features

**Pull request merged**
