### PR TITLE
Update bazelbuild/rules_go to 0.24.13 (preparing for go 1.16 upgrade)

### PR DESCRIPTION
**Pull request by pinglamb**
**What type of PR is this?**

> Other

**What does this PR do? Why is it needed?**

Update `rules_go` to `0.24.13` which starts to support go 1.16. https://github.com/bazelbuild/rules_go/releases/tag/v0.24.13

This is for preparing the go 1.16 upgrade. Further changes/PRs are needed.

**Which issues(s) does this PR fix?**

**Other notes for review**

### CODE REVIEW

**Review by nisdas — CHANGES_REQUESTED** [review]
You have to register the toolchain correctly too below:

```go
go_register_toolchains(
    go_version = "1.16",
    nogo = "@//:nogo",
)
```
Also go.mod needs to be updated to account for the new go version, and there are some breaking changes in v1.16 (deprecating of ioutil) that we have to patch in too. Also we will want to use the new embed directive in a few places.

**Comment by pinglamb** [comment]
@nisdas This PR is intended to just update the `rules_go` to `0.24.13`. I plan to create multiple PRs for updating to go 1.16 and hope to keep each change small.

**Review by terencechain — CHANGES_REQUESTED** [review]
Let's hold off on upgrading 1.16 too fast

Much rather be slow and diligent here

**Review by prestonvanloon — APPROVED** [review]
Looks good! 

@terencechain this doesn't update go to 1.16 yet. That can come in another PR.

**Review by terencechain — APPROVED** [review]

**Review by nisdas — APPROVED** [review]
Thanks for clarifying @pinglamb , looks good to me in that case

**Pull request merged**
