### PR TITLE
Prevent invalid pending attestations

### PR DESCRIPTION
**Pull request by prestonvanloon**
This prevents a proposer from requesting pending attestation that will immediately fail the compute state root RPC method.

This logic is intended to match the block processing attestation validity logic. 
https://github.com/prysmaticlabs/prysm/blob/f801bfedcf39dfa6e367b920d043cd58fa5c0175/beacon-chain/core/blocks/block_operations.go#L472-L493

Regression test for the invalid block scenario to come in #2027

### CODE REVIEW

**Comment by rauljordan** [comment]
Hi @prestonvanloon can this be closed? It was merged in a recent PR I believe.

**Comment by prestonvanloon** [comment]
I don’t think it was merged. I just synced with master. I’ll update shortly

**Comment by prestonvanloon** [comment]
Going to defer regression test to another PR to check this in more urgently. I’ll create an issue for it to track.

**Comment by prestonvanloon** [comment]
Filed #2027

**Comment by prestonvanloon** [comment]
Sanity check saw chain advance beyond slot 200 in multinode deployment with no RPC errors reported to jaeger

**Pull request merged**
