### PR TITLE
Remove redundant request to get duties of next epoch in validator

### LINKED ISSUE #8194: Redundant request for getting duties for the next epoch
https://github.com/prysmaticlabs/prysm/blob/4c6e0c5f4656b7f0b6a7df065d4ec0a3b802d4e0/validator/client/validator.go#L381

No needed to send one more request for getting duties of the next epoch. It is possible to get the same data from the first response `resp.GetNextEpochDuties()` without sending one more RPC request.

### PR DESCRIPTION
**Pull request by KaanKC**
**What type of PR is this?**

> Other

Enhancement

**What does this PR do? Why is it needed?**
Just a small refactor that removes an unnecessary RPC request. The data is already included in the prior response.

**Which issues(s) does this PR fix?**

Fixes #8194 

**Other notes for review**

### CODE REVIEW

**Review by terencechain — APPROVED** [review]

**Comment by nisdas** [comment]
This PR breaks e2e for some reason, none of the e2e test runs have passed.

**Comment by KaanKC** [comment]
Any idea on what might be the issue?

**Comment by prestonvanloon** [comment]
Have you tested this at runtime? E2E is failing consistently which might indicate there is a fundamental issue with this change.

**Comment by KaanKC** [comment]
No, I didn't. Didn't expect it to be a breaking change since I thought both the existing code and my changes were accessing the same data. At least according to the issue. I guess now we know that that is not the case. PR should probably be closed together with the issue.

**Comment by nisdas** [comment]
No worries, thanks for taking this issue up @KaanKC , your effort is appreciated here. Given what terence has mentioned about this being an issue with deeper re-orgs, it might be best to not use the cached value of the next epoch. Will be closing the PR for now and updating the issue.

**Comment by prestonvanloon** [comment]
Actually, I think we may have been wrong here @nisdas and @terencechain. 
The next epochs duties here is only used as an early signal for aggregators. 
I'm going to cherry pick these changes into another PR.

**Pull request closed without merging**
