### PR TITLE
Use Genesis Time From the State

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Feature Reversion

**What does this PR do? Why is it needed?**

- [x] Previously through #6545, the genesis time was hardcoded as a param in the config. However this has introduced issues
where the genesis time is 0 in the event it is not set. This is highly susceptible to leading to incorrect use of the param. In light of how important it is in the node to have the correct genesis time. This param is remove from all methods that normally call it. We now retrieve it from the genesis state.

**Which issues(s) does this PR fix?**

N.A

**Other notes for review**

### CODE REVIEW

**Comment by farazdagi** [comment]
Discussed on Discord: `helpers/slot_epoch.go:GenesisTime()` method usage has been refactored everywhere, so we can remove the method itself as well.

**Comment by terencechain** [comment]
Marking this as blocked. Let's merge https://github.com/prysmaticlabs/prysm/pull/7178 first

**Comment by terencechain** [comment]
@nisdas take a final look before i approve please

**Comment by nisdas** [comment]
@terencechain I dont think we need this anymore :laughing:

**Pull request closed without merging**
