### PR TITLE
Standardize Beacon Chain and Validator Client Parameter Definitions

### LINKED ISSUE #656: Standardize params.Config in Beacon-Chain and Validator Projects
Hi all,

We currently have two different ways of getting configuration params in both projects, the beacon chain uses params.GetConfig() while the validator uses params.DemoConfig() or params.DefaultConfig(). This is a bit confusing and would be best if we just stick to the way the beacon chain does so. This obfuscates what type of config parameters the system is using and lets the cli and node handle this effectively through a flag. This is preferred.

A PR to close this would change validator's params package to match the way the beacon-chain handles its params.

### PR DESCRIPTION
**Pull request by cyberbono3**
Resolves #656

# Description

Standartize params in Beacon-Chain and Validator Projects
1. move validator/params and beacon-chain/params to shared/params
2. instead of SetEnv define SetDemoBeaconConfig() that handles config parameters 
3. for clarity rename functions that handle validator and beacon-chain configs.

### CODE REVIEW

**Comment by cyberbono3** [comment]
Sorry about that ) which merges have I reverted?

**Comment by terenc3t** [comment]
Hi @cyberbono3 please let us know if you need any additional help on this

**Comment by rauljordan** [comment]
Hi @cyberbono3 do you have an update on this PR?

**Comment by rauljordan** [comment]
Closing as this is dealt with by #736

**Pull request closed without merging**
