### PR TITLE
Add List Blocks RPC For Altair

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Feature Addition

**What does this PR do? Why is it needed?**

- [x] Adds in a new Altair Specific Method to retrieve Altair Blocks.

**Which issues(s) does this PR fix?**

Part of #8638 

**Other notes for review**

### CODE REVIEW

**Review by prestonvanloon — COMMENTED** [review]
This looks like a lot of duplicated code from the v1 ListBlocks,can anything be refactored to reduce the diff?

I imagine the only real difference here is the return response type to be altair blocks?

**Comment by prestonvanloon** [comment]
The delta between beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go beacon-chain/rpc/prysm/v2/beacon/blocks.go in `ListBlocks` is fairly minimal. We could deduplicate a lot of this code with some abstractions and refactoring.

**Comment by nisdas** [comment]
@prestonvanloon I can try cleaning this up to be have less duplication.

**Review by prestonvanloon — APPROVED** [review]
Thanks for making those changes!

**Pull request merged**
