### PR TITLE
Consider missing validator count for performance metric

### LINKED ISSUE #4927: Aggregated voting summary includes validators that haven't been activated yet
Aggregated voting summary should probably not include validators that could not have made attestations during the epoch. Or it's missing some active ones. The following summary should have 10 active and 10 waiting to be activated (some having deposit included, some waiting for deposit inclusion). So if it was the active 10 the percentages should be multiples of 0.10.

```
[2020-02-22 22:33:12]  INFO validator: Submitted new attestations AggregatorIndices=[] AttesterIndices=[28764] BeaconBlockRoot=0x9b5a9d406188 CommitteeIndex=4 Slot=316065 SourceEpoch=9876 SourceRoot=0x6d3bc4f1177f TargetEpoch=9877 TargetRoot=0x9b5a9d406188
[2020-02-22 22:33:48]  INFO validator: Submitted new attestations AggregatorIndices=[] AttesterIndices=[32217] BeaconBlockRoot=0xd6ca319abb44 CommitteeIndex=6 Slot=316068 SourceEpoch=9876 SourceRoot=0x6d3bc4f1177f TargetEpoch=9877 TargetRoot=0x4aed17f413e9
[2020-02-22 22:34:00]  INFO validator: Submitted new attestations AggregatorIndices=[] AttesterIndices=[32220] BeaconBlockRoot=0x83349fa6e9b8 CommitteeIndex=8 Slot=316069 SourceEpoch=9876 SourceRoot=0x6d3bc4f1177f TargetEpoch=9877 TargetRoot=0x4aed17f413e9
[2020-02-22 22:34:12]  INFO validator: Submitted new attestations AggregatorIndices=[] AttesterIndices=[32223] BeaconBlockRoot=0x83349fa6e9b8 CommitteeIndex=6 Slot=316070 SourceEpoch=9876 SourceRoot=0x6d3bc4f1177f TargetEpoch=9877 TargetRoot=0x4aed17f413e9
[2020-02-22 22:35:12]  INFO validator: Submitted new attestations AggregatorIndices=[32216] AttesterIndices=[32216] BeaconBlockRoot=0xe7dce38a199d CommitteeIndex=9 Slot=316075 SourceEpoch=9876 SourceRoot=0x6d3bc4f1177f TargetEpoch=9877 TargetRoot=0x4aed17f413e9
[2020-02-22 22:35:24]  INFO validator: Submitted new attestations AggregatorIndices=[] AttesterIndices=[32222] BeaconBlockRoot=0x06f1b66185f9 CommitteeIndex=5 Slot=316076 SourceEpoch=9876 SourceRoot=0x6d3bc4f1177f TargetEpoch=9877 TargetRoot=0x4aed17f413e9
[2020-02-22 22:35:36]  INFO validator: Submitted new attestations AggregatorIndices=[] AttesterIndices=[32221] BeaconBlockRoot=0xabe7faaee4fc CommitteeIndex=2 Slot=316077 SourceEpoch=9876 SourceRoot=0x6d3bc4f1177f TargetEpoch=9877 TargetRoot=0x4aed17f413e9
[2020-02-22 22:36:36]  INFO validator: Submitted new attestations AggregatorIndices=[] AttesterIndices=[32219] BeaconBlockRoot=0xa398ef28a245 CommitteeIndex=8 Slot=316082 SourceEpoch=9876 SourceRoot=0x6d3bc4f1177f TargetEpoch=9877 TargetRoot=0x4aed17f413e9
[2020-02-22 22:37:36]  INFO validator: Submitted new attestations AggregatorIndices=[] AttesterIndices=[32215] BeaconBlockRoot=0x3ba37bd82eec CommitteeIndex=4 Slot=316087 SourceEpoch=9876 SourceRoot=0x6d3bc4f1177f TargetEpoch=9877 TargetRoot=0x4aed17f413e9
[2020-02-22 22:38:00]  INFO validator: Submitted new attestations AggregatorIndices=[32218] AttesterIndices=[32218] BeaconBlockRoot=0x65b3d98164fe CommitteeIndex=7 Slot=316089 SourceEpoch=9876 SourceRoot=0x6d3bc4f1177f TargetEpoch=9877 TargetRoot=0x4aed17f413e9
[2020-02-22 22:39:12]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=false epoch=9877 inclusionDistance=1 inclusionSlot=316002 newBalance=3.107376261 oldBalance=3.107377616 percentChange=-0.00004% pubKey=0x8189e4962cbc82fc
[2020-02-22 22:39:12]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=9877 inclusionDistance=1 inclusionSlot=316021 newBalance=3.095676024 oldBalance=3.095669866 percentChange=0.00020% pubKey=0x9495b5725cd7bc37
[2020-02-22 22:39:12]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=9877 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.10849089 oldBalance=3.108503904 percentChange=-0.00042% pubKey=0xae5cce5a318fff05
[2020-02-22 22:39:12]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=9877 inclusionDistance=2 inclusionSlot=316017 newBalance=3.105910469 oldBalance=3.105906005 percentChange=0.00014% pubKey=0x885982b3db105c62
[2020-02-22 22:39:12]  INFO validator: Validator not in beacon chain pubKey=0xa06d83d0a62bce72
[2020-02-22 22:39:12]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=9877 inclusionDistance=2 inclusionSlot=316030 newBalance=3.106854516 oldBalance=3.106850052 percentChange=0.00014% pubKey=0xb007dd53f8079256
[2020-02-22 22:39:12]  INFO validator: Previous epoch voting summary correctlyVotedHead=true correctlyVotedSource=true correctlyVotedTarget=true epoch=9877 inclusionDistance=2 inclusionSlot=316027 newBalance=3.105946682 oldBalance=3.105937391 percentChange=0.00030% pubKey=0xa662fc6715f44c12
[2020-02-22 22:39:12]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=9877 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x8c8b7961a450eddf
[2020-02-22 22:39:12]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=9877 inclusionDistance=1 inclusionSlot=316009 newBalance=3.106893991 oldBalance=3.106887629 percentChange=0.00020% pubKey=0xa075b8a35501e3f8
[2020-02-22 22:39:12]  INFO validator: Validator not in beacon chain pubKey=0x97e6317650a1896c
[2020-02-22 22:39:12]  INFO validator: Validator not in beacon chain pubKey=0x84c6507fd1fa61cd
[2020-02-22 22:39:12]  INFO validator: Validator not in beacon chain pubKey=0xaa5722114cecbcca
[2020-02-22 22:39:12]  INFO validator: Validator not in beacon chain pubKey=0x84fb94fa1cea68b2
[2020-02-22 22:39:12]  INFO validator: Validator not in beacon chain pubKey=0x94eec02896f6d75f
[2020-02-22 22:39:12]  INFO validator: Validator not in beacon chain pubKey=0xa4d8f8a8048450b4
[2020-02-22 22:39:12]  INFO validator: Previous epoch aggregated voting summary attestationInclusionPercentage=0.46 correctlyVotedHeadPercentage=0.08 correctlyVotedSourcePercentage=0.46 correctlyVotedTargetPercentage=0.38 epoch=9877
```

### PR DESCRIPTION
**Pull request by terencechain**
This fixes #4927 

Here's the bug, validator performance responses the following:
```
{
pubKey: 0xA, 0xB, 0xC, 0xD, 0xE, 0xC
missing validators: 0xA, 0xB, 0xC
}
```
The length of `resp.InclusionSlots` will be 3 (0xD, 0xE, 0xC), which means we will not be able to count them because their indices 3-5 is all greater than or equal to 3

### CODE REVIEW

**Comment by terencechain** [comment]
cc @SuburbanDad

**Comment by zediir** [comment]
This will now include those keys in the percentages that don't have their deposit included yet and fixes the missing actual attestation results. But it will also include those that have deposit included and print "validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=9971 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 **newBalance=3.2** **oldBalance=3.2** **percentChange=0.00000%** pubKey=0xa4d8f8a8048450b4" for those rows until they are activated. This still skews the percentages towards a worse than actual number.

**Comment by terencechain** [comment]
> This will now include those keys in the percentages that don't have their deposit included yet and fixes the missing actual attestation results. But it will also include those that have deposit included and print
> 
> "validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=9971 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 **newBalance=3.2** **oldBalance=3.2** **percentChange=0.00000%** pubKey=0xa4d8f8a8048450b4"
> 
> for those rows until they are activated.
> This still skews the summary percentages towards a worse than actual number.

I see. This is tricky. Sorry for asking you to try since we don't have the same set up. Feel free to share the key file with us so we can try it here.
I think the latest commit bbcd75e should fix this, let me know! : )

**Comment by zediir** [comment]
Using wallet keymanager so no keyfile :)

results:

```
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=3 inclusionSlot=322338 newBalance=3.106379827 oldBalance=3.106376008 percentChange=0.00012% pubKey=0xb007dd53f8079256
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=1 inclusionSlot=322309 newBalance=3.106628175 oldBalance=3.106621848 percentChange=0.00020% pubKey=0x87bc8de7abd928a3
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.105838826 oldBalance=3.10585172 percentChange=-0.00042% pubKey=0x8c8b7961a450eddf
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0xa075b8a35501e3f8
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x84fb94fa1cea68b2
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x97e6317650a1896c
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x94eec02896f6d75f
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=1 inclusionSlot=322310 newBalance=3.095868113 oldBalance=3.09586199 percentChange=0.00020% pubKey=0x9495b5725cd7bc37
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x8dd8796ed6cca18c
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=1 inclusionSlot=322334 newBalance=3.108556897 oldBalance=3.10855057 percentChange=0.00020% pubKey=0xae5cce5a318fff05
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=2 inclusionSlot=322324 newBalance=3.107425817 oldBalance=3.107421371 percentChange=0.00014% pubKey=0x8189e4962cbc82fc
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.107015047 oldBalance=3.107027941 percentChange=-0.00041% pubKey=0xa662fc6715f44c12
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0xa4d8f8a8048450b4
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x84c6507fd1fa61cd
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0xaa5722114cecbcca
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=1 inclusionSlot=322334 newBalance=3.106904689 oldBalance=3.106898362 percentChange=0.00020% pubKey=0xa2d66df968a33d74
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=1 inclusionSlot=322322 newBalance=3.106702374 oldBalance=3.106696047 percentChange=0.00020% pubKey=0xa9899d5bba69f106
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=1 inclusionSlot=322314 newBalance=3.106164375 oldBalance=3.106158048 percentChange=0.00020% pubKey=0x885982b3db105c62
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x863705e15966e0d1
[2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0xa06d83d0a62bce72
[2020-02-23 19:40:00]  INFO validator: Previous epoch aggregated voting summary attestationInclusionPercentage=0.40 correctlyVotedHeadPercentage=0.00 correctlyVotedSourcePercentage=0.40 correctlyVotedTargetPercentage=0.40 epoch=10074
```

18 hrs until my new validators will activate.
Sent the keystore.json and wallets as a tarball to you on discord.

**Comment by terencechain** [comment]
> Using wallet keymanager so no keyfile :)
> 
> results:
> 
> ```
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=3 inclusionSlot=322338 newBalance=3.106379827 oldBalance=3.106376008 percentChange=0.00012% pubKey=0xb007dd53f8079256
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=1 inclusionSlot=322309 newBalance=3.106628175 oldBalance=3.106621848 percentChange=0.00020% pubKey=0x87bc8de7abd928a3
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.105838826 oldBalance=3.10585172 percentChange=-0.00042% pubKey=0x8c8b7961a450eddf
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0xa075b8a35501e3f8
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x84fb94fa1cea68b2
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x97e6317650a1896c
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x94eec02896f6d75f
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=1 inclusionSlot=322310 newBalance=3.095868113 oldBalance=3.09586199 percentChange=0.00020% pubKey=0x9495b5725cd7bc37
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x8dd8796ed6cca18c
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=1 inclusionSlot=322334 newBalance=3.108556897 oldBalance=3.10855057 percentChange=0.00020% pubKey=0xae5cce5a318fff05
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=2 inclusionSlot=322324 newBalance=3.107425817 oldBalance=3.107421371 percentChange=0.00014% pubKey=0x8189e4962cbc82fc
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.107015047 oldBalance=3.107027941 percentChange=-0.00041% pubKey=0xa662fc6715f44c12
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0xa4d8f8a8048450b4
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x84c6507fd1fa61cd
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0xaa5722114cecbcca
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=1 inclusionSlot=322334 newBalance=3.106904689 oldBalance=3.106898362 percentChange=0.00020% pubKey=0xa2d66df968a33d74
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=1 inclusionSlot=322322 newBalance=3.106702374 oldBalance=3.106696047 percentChange=0.00020% pubKey=0xa9899d5bba69f106
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=true epoch=10074 inclusionDistance=1 inclusionSlot=322314 newBalance=3.106164375 oldBalance=3.106158048 percentChange=0.00020% pubKey=0x885982b3db105c62
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0x863705e15966e0d1
> [2020-02-23 19:40:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10074 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.2 oldBalance=3.2 percentChange=0.00000% pubKey=0xa06d83d0a62bce72
> [2020-02-23 19:40:00]  INFO validator: Previous epoch aggregated voting summary attestationInclusionPercentage=0.40 correctlyVotedHeadPercentage=0.00 correctlyVotedSourcePercentage=0.40 correctlyVotedTargetPercentage=0.40 epoch=10074
> ```
> 
> 18 hrs until my new validators will activate.
> Sent the keystore.json and wallets as a tarball to you on discord.

Thanks for the result. That looks right to me. 12/20 validators attestations didn't get included. 8/20 validators attestations got included. `0.4`

**Comment by zediir** [comment]
But is it really correct? As 10 out of those validators never even made any attestations as they were not activated yet so should they be counted? So should it be 8/20 or 8/10?

**Comment by terencechain** [comment]
> But is it really correct? As 10 out of those validators never even made any attestations as they were not activated yet so should they be counted? So should it be 8/20 or 8/10?

That's correct. This PR doesn't address the fact pending activation validators get accounted in the stats. To keep this PR lean, the next PR will address that. Right now this PR only addresses accounting of missing validator performance metric

**Pull request merged**
