### PR TITLE
Add value for MaxBuilderEpochMissedSlots

### LINKED ISSUE #14275: Update differences between code and help commands
## Description
- The actual source code and the behavior of the help command are different and need to be updated to avoid confusion.

https://github.com/prysmaticlabs/prysm/blob/6f7976766d23db64d5680266b542f1b531b07bc6/cmd/beacon-chain/flags/base.go#L23-L26

To make it more friendly, Value should be included.
This should also be reflected in the official documentation.

### 🔬 Minimal Reproduction

1. Build Prysm. (Docker is also acceptable)
2. Show help command
3. Check `max-builder-epoch-missed-slots`

### Platform(s)

Linux (x86), Mac (Apple Silicon)

### What version of Prysm are you running? (Which release)

v5.0.3

### PR DESCRIPTION
**Pull request by bnovil**
**What type of PR is this?**

 Bug fix

**What does this PR do? Why is it needed?**
Add value for MaxBuilderEpochMissedSlots to make it consistent with the documentation,  https://docs.prylabs.network/docs/advanced/builder

> Circuit breaker
The circuit breaker is a safety feature for falling back to local execution when using a builder. This occurs when the builder or client using the builder endpoints encounters issues that cause missed blocks. By default, the circuit breaker will be triggered after 3 slots are consecutively missed or 5 slots are missed in an epoch, but this can be configured through the --max-builder-consecutive-missed-slots and max-builder-epoch-missed-slots flags.

**Which issues(s) does this PR fix?**

Fixes #14275

**Other notes for review**

### CODE REVIEW

**Comment by prestonvanloon** [comment]
@terencechain please review this. Why is there no default flag value and is it safe to add one?

**Comment by potuz** [comment]
> @terencechain please review this. Why is there no default flag value and is it safe to add one?
> 
> edit: introduced in #11215

I thought this was covered here
https://github.com/prysmaticlabs/prysm/blob/develop/config/params/mainnet_config.go#L265

It needs different values per chain, I'd close this one @prestonvanloon

**Comment by prestonvanloon** [comment]
Thanks @potuz.

We can either close this entirely or merge with a comment mentioning that the defaults are on a network basis and we can provide the default value for mainnet in the description such that users can understand from the help text.

@bnovil What do you think?

**Comment by bnovil** [comment]
> Thanks @potuz.
> 
> We can either close this entirely or merge with a comment mentioning that the defaults are on a network basis and we can provide the default value for mainnet in the description such that users can understand from the help text.
> 
> @bnovil What do you think?

I see. I'd like to update the description to make it easier to understand. Thanks for your explanation.

**Review by prestonvanloon — APPROVED** [review]

**Pull request merged**
