### PR TITLE
Cleanup of Keymanager Deleter interface

### PR DESCRIPTION
**Pull request by michaelneuder**
**What type of PR is this?**
Refactor

**What does this PR do? Why is it needed?**
This PR addresses the account deletion code and refactors it as part of https://github.com/prysmaticlabs/prysm/issues/9883. 

The key change is making the `Deleter` interface a mandatory part of the `IKeymanager` interface (in `validator/keymanager/types.go`). This is inline with the other changes in this refactor: https://github.com/prysmaticlabs/prysm/pull/10313 & https://github.com/prysmaticlabs/prysm/pull/10382. 

This addition to the interface cleans up the following pieces of code:
- `validator/accounts/accounts_delete.go`: we no longer have to do the type assertion against the Keymanager into the `keymanager.Deleter` type. Instead we can just call `.DeleteKeystores` on the Keymanager and if that keymanager type doesn't support the operation it will just return an error. 
- `validator/rpc/accounts.go`: we no longer need to conditionally check on the keymanager kind before calling `DeleteAccount`. We know that if it is the wrong keymanager type, it will just fail fast and return the error.
- `validator/rpc/standard_api.go`: we no longer have to do the type assertion against the Keymanager into the `keymanager.Deleter` type. We can just call `.DeleteKeystores` on the keymanager directly. 
- `validator/accounts/accounts.go`: we can rename `Config` to `DeleteConfig` to increase the specificity of the type, because it is only used to configure the delete operation. Additionally, we can remove the `*wallet.Wallet` field from the type because that is unused.

**Which issues(s) does this PR fix?**
This is part of the keymanager refactor defined in https://github.com/prysmaticlabs/prysm/issues/9883.

### CODE REVIEW

**Comment by michaelneuder** [comment]
will fix check failure when I get home tonight. just need to implement the interface on the mock keymanager.

**Comment by michaelneuder** [comment]
OK! Added to the mock functions.

**Comment by michaelneuder** [comment]
Confused by the Check failing. I ran `go mod tidy` and added the `go.sum` file to the PR, but it is still failing. is there something I am missing here?

**Comment by michaelneuder** [comment]
> > Confused by the Check failing. I ran `go mod tidy` and added the `go.sum` file to the PR, but it is still failing. is there something I am missing here?
> 
> Maybe you needed the `-compat-1.17` flag if using go 1.18 on your host. I pushed this for you.

thanks, Preston!

**Review by james-prysm — APPROVED** [review]
All the key manager types do have the ability to delete so let's try this refactor for now.

**Pull request merged**
