### PR TITLE
Node and chain info RPC calls

### PR DESCRIPTION
**Pull request by mcdee**
This implements the `GetNodeInfo` and `GetChainInfo` RPC calls.  It is a relatively big patch as the APIs are used internally with a number of other processes, but a large chunk of the alterations are in tests where mocked services exposed variables which ultimately resulted in clashes with a newly-added function.

This also provides a slightly odd patch for ethereumapis: the work on which this was based went missing from the ethereumapis repo so it's being included in the patch for now.  When the relevant items are added back in to ethereumapis another PR can be raised here to update the ethereumapis version and patch, but for now it makes sense to get this in to avoid merge conflicts with the altered API calls.

### CODE REVIEW

**Comment by terencechain** [comment]
Can we target master for this?

**Comment by mcdee** [comment]
We decided against this when looking at the API change.  Firstly, it is a breaking change as it removes some existing APIs.  Secondly, it involves items (_e.g._ GenesisValidatorsRoot, ForkVersionSchedule) that are only present in 0.11

**Comment by terencechain** [comment]
We are trying to avoid non-breaking changes going into v0.11 branch and as you can see there's a descent amount of diff with the mock stuff.

Is there a way to separate out breaking and non breaking and only merge the breaking changes into v0.11?

**Comment by mcdee** [comment]
The piece that is non-breaking is the addition of the `GetNodeInfo` and `GetChainInfo` RPC calls, but they have 0.11-specific items in them.

It would be possible to put these calls in to master with a subset of the functionality, but I don't think that would achieve a lot as we'd then have to merge that in to 0.11 from master so we could add the 0.11 items and I don't think it would result in a significantly smaller patch.

**Comment by mcdee** [comment]
If the amount of change is a serious issue an option would be to add `GetNodeInfo` and `GetChainInfo` to v0.11 and mark the existing calls as deprecated but do not remove them.  This should significantly reduce the size of the patch, with the downside being that there will be overlapping functionality in the API calls.

**Comment by mcdee** [comment]
Too much movement in the codebase to maintain this PR.

**Pull request closed without merging**
