### PR TITLE
Fix issue with direct wallet's password being overwritten by incorrect password during import.

### LINKED ISSUE #7211: Providing a wrong pass followed by a correct pass during accounts-v2 import overwrites the password
#🐞 Bug Report
### Description

In current master, if you have a direct-type wallet and try to import using accounts-v2 import, something like the following happens:
Attempt 1) Try the correct password <--- All goes well
Attempt 2) Try an incorrect password and the program keeps looping until you provide a good password. <--- The first (incorrect) password becomes the new password after the new keystore is written.
Attempt 3) The previously incorrect password now works.

```
		enc, password, err = askUntilPasswordConfirms(decryptor, keystoreFile)
		if err != nil {
			return errors.Wrap(err, "could not confirm password via prompt")
		}
```

The password variable that is returned by askUntilPasswordConfirms() is ignored and the old (wrong) password remains.

### Has this worked before in a previous version?
Unsure

## 🔬 Minimal Reproduction

See above

## 🔥 Error

As described above.

## 🌍  Your Environment

**Operating System:**

Windows 10 as well as a docker container within an Ubuntu VM.

**What version of Prysm are you running? (Which release)**

3147a5ee01342788d3b1d1f8c52a85ecacc80ded

**Anything else relevant (validator index / public key)?**
No

### PR DESCRIPTION
**Pull request by dv8silencer**
**What type of PR is this?**
> Bug fix

From the issue:  
In current master, if you have a direct-type wallet and try to import using accounts-v2 import, something like the following happens:
Attempt 1) Try the correct password <--- All goes well
Attempt 2) Try an incorrect password and the program keeps looping until you provide a good password. <--- The first (incorrect) password becomes the new password after the new keystore is written.
Attempt 3) The previously incorrect password now works.

**What does this PR do? Why is it needed?**
Resolves a bug (see below).

```
enc, password, err = askUntilPasswordConfirms(decryptor, keystoreFile)
		if err != nil {
			return errors.Wrap(err, "could not confirm password via prompt")
		}
```
The password variable that is returned by askUntilPasswordConfirms() is ignored and the old (wrong) password remains.

**Which issues(s) does this PR fix?**

Fixes #7211 

**Other notes for review**

I create a 'setter' as well as overwrite the initially incorrect password in the Wallet with the one that works after the error check.

Building with these changes resolves the issue.

### CODE REVIEW

**Comment by dv8silencer** [comment]
Realize now that this broke some tests...  Looking into it.

**Review by prestonvanloon — CHANGES_REQUESTED** [review]
Please add regression test

**Comment by dv8silencer** [comment]
Converted to draft while I figure out the regression test.

**Comment by dv8silencer** [comment]
initializeAccountKeystore() in validator/keymanager/v2/direct/direct.go calls askUntilPasswordConfirms() which then calls promptutil.PasswordPrompt (in prompt.go) which then calls terminal.ReadPassword:

`terminal.ReadPassword(int(os.Stdin.Fd()))`

The terminal package (x/crypto/ssh/terminal) is an external dependency used to read passwords.  This call is also deep in flow.  So in order to be able to call a higher-level function from a test, an idea was to create a global in prompt.go like: 

```go
// InputType will default to os.Stdin but can be altered for testing purposes.
var InputType StdinOrOtherFile = os.Stdin

type StdinOrOtherFile interface {
    io.Reader
    Fd() uintptr
}
```

And then change the call to `terminal.ReadPassword(int(InputType.Fd()))` and allow it to remain = os.Stdin (default) for usual execution and for a test to switch it to a file for testing.  Unfortunately, at least in Windows, creating a file, putting in data, ensuring it is written to disk, (not closing it), and setting InputType equal to it, did not work.  Windows would say it was an invalid Handle when the terminal package tried to use it here:

```go
func ReadPassword(fd int) ([]byte, error) {
	var st uint32
	if err := windows.GetConsoleMode(windows.Handle(fd), &st); err != nil {
		return nil, err
	}
```

**I believe terminal needs an actual Windows "console" handle not just any file**.  Possibly this way of tackling the issue could be salvaged in Unix-type systems but I think there would be portability issues.  **Thus I switched the design:  Create a global function variable in prompt.go set to a default function that simply "Forwards" to terminal.ReadPassword(), but can be changed to any other function.  The test changes this function to one that provides passwords without really interacting with Stdin**  Then the call can be changed from 
`terminal.ReadPassword(int(os.Stdin.Fd()))` to `PasswordReader(os.Stdin)`, the latter being defined like 

```go
// PasswordReaderFunc takes in a *file and returns a password using the terminal package
func passwordReaderFunc(file *os.File) ([]byte, error) {
	pass, err := terminal.ReadPassword(int(file.Fd()))
	return pass, err
}

// PasswordReader has passwordReaderFunc as the default but can be changed for testing purposes.
var PasswordReader func(file *os.File) ([]byte, error) = passwordReaderFunc
```

**Comment by dv8silencer** [comment]
**To see the test detect failure (i.e. test combined with live bug)**
Clone https://github.com/dv8silencer/prysm.git and checkout branch dv8-PR-7212-Regression
Build
cd into validator/accounts/v2/ and run the following
go test -run Test_KeysConsistency_Direct
FAIL

**To see test combined with bug fix:**
checkout branch dv8-iPendOverwImport (the branch in this PR) and build
cd into validator/accounts/v2 and run the following
go test -run Test_KeysConsistency_Direct
PASS

**Review by prestonvanloon — APPROVED** [review]
Looks great! thanks!

**Pull request merged**
