### PR TITLE
remove db validator use

### PR DESCRIPTION
**Pull request by shayzluf**
[Part of] #5327

---

# Description
remove the use of db calls for get validators and set validators in db throughout the repo

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Please target master

**Comment by prestonvanloon** [comment]
#5327 is meant to only remove tracking validator indices from the database. Please reduce the scope of this PR to satisfy only the requirements for #5327 or split into multiple PRs

**Comment by shayzluf** [comment]
> #5327 is meant to only remove tracking validator indices from the database. Please reduce the scope of this PR to satisfy only the requirements for #5327 or split into multiple PRs

can you please clarify what you mean by remove tracking validator indices from the database

**Comment by prestonvanloon** [comment]
> can you please clarify what you mean by remove tracking validator indices from the database

We save the validator indices to the database unnecessarily. Please see the description in #5327

**Pull request closed without merging**
