### PR TITLE
mark pre-merge and pre-bellatrix blocks as valid

### PR DESCRIPTION
**Pull request by potuz**
Mark pre-merge blocks as not optimistic

### CODE REVIEW

**Comment by rkapka** [comment]
A unit test perhaps?

**Comment by potuz** [comment]
> A unit test perhaps?

this is for kiln,  but yes thanks, if this passes bellatrixe2e will add a unit test and update to develop

**Comment by potuz** [comment]
Closing in favor of #10398

**Comment by potuz** [comment]
Closing in favor of #10398

**Pull request closed without merging**
