### PR TITLE
Update run time to v0.9

### PR DESCRIPTION
**Pull request by terencechain**
This PR merges `v0.9` branch to `master`

What's tested:
- 1 beacon node 64 validators with eth1 mock rpc
- 2 beacon nodes 128 validators each with eth1 mock rpc

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Anything still TODO for v0.9?

**Comment by terencechain** [comment]
> Anything still TODO for v0.9?

I'd way more granular local testing like multi nodes with static peers, in the mean time please take a look at this PR for reviews

**Comment by nisdas** [comment]
@terencechain build is failing

**Comment by prestonvanloon** [comment]
Just needs #3962 then we can test a deployment.

**Comment by prestonvanloon** [comment]
#3962 only affects historical data and is not blocking for testnet release.

**Comment by prestonvanloon** [comment]
Blocked by https://github.com/prysmaticlabs/prysm/issues/3965

**Comment by prestonvanloon** [comment]
Ready for final review. This is currently running in testnet

**Comment by prestonvanloon** [comment]
Merging at 22:00 UTC (2.5 hours from now) unless any blockers or issues discovered.

**Pull request merged**
