### PR TITLE
Add in Balance Safety Check

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Bug Fix

**What does this PR do? Why is it needed?**

- [x] When performing an addition of unsigned integers, we make sure that the values do not overflow and return 
an error in that case no matter how unlikely it would be to hit this case.
- [x] Add in regression tests.

**Which issues(s) does this PR fix?**

N.A

**Other notes for review**

### CODE REVIEW

**Review by prestonvanloon — APPROVED** [review]

**Comment by prestonvanloon** [comment]
Can this go into develop?

**Comment by nisdas** [comment]
@prestonvanloon I will need all core code from `hf1` be merged into develop for that. I can wait till that is done and then change the base branch in this PR to `develop`

**Review by kasey — APPROVED** [review]

**Comment by rauljordan** [comment]
I think core is already in develop, so we should be fine to retarget this one @nisdas

**Review by terencechain — COMMENTED** [review]
We should retarget this to develop

**Comment by prestonvanloon** [comment]
@nisdas ping on this. Is this a v2 candidate?

**Review by terencechain — APPROVED** [review]

**Pull request merged**
