### PR TITLE
Merge validator keys

### PR DESCRIPTION
**Pull request by rkapka**
**What type of PR is this?**
> Feature

**What does this PR do? Why is it needed?**

It creates a new `validator accounts merge` command that allows to copy validator keys from several directories into a single directory and protect all of them with the same password. I chose copying over moving over so that the old validators are left intact in case something goes wrong with the merge.

**Which issues(s) does this PR fix?**

It is the first PR in a series of PRs addressing #5638.

**Other notes for review**

This PR is currently a draft because of the following:
1. There are no tests yet.
2. Even though I am able to run the command using GoLand's Bazel debugging, I cannot run it via `prysm.sh`. I get this meesage: `No help topic for 'merge'`. I probably didn't register the new command somewhere. Can anyone help me?

I noticed several things while working on this PR:
1. Something is wrong with typing in passwords. I didn't want to ask the user to confirm the password for source directories, but this caused strange behaviour. While merging two directories, when I entered the password for the first directory the script tried to process also the second directory using this password. This issue might have something to do with the fact that when confirming password is turned off, you have to hit `Return` twice to proceed.
2. It is not possible to tell the user whether a directory has been successfully merged (and, as a result, it's not possible to break the loop in case merging failed) because the key management library only produces warnings when decryption failed (e.g. when the password is wrong).
3. It is possible to start up a validator when providing an incorrect password. The warning mentioned above is displayed and the validator does not crash. It is not related to this PR, but I found it rather strange.

### CODE REVIEW

**Comment by rkapka** [comment]
I got so excited about creating this PR that I forgot to check if everything builds successfully after merging with origin. Sorry about that...

**Comment by rkapka** [comment]
I wrote a test which verifies that all keys are copied to the target directory. I wanted to write another one verifying that the keys are encrypted using the new password, but it's impossible to do because of the aforementioned issue with warnings issued by the key management library (`keystore.go`). This is a considerable problem in my opinion because the encryption functionality is very important here. The library has been copied from go-ethereum and modified by you guys in 2018. Is it OK to make further changes to it? Maybe I could add another parameter to allow the library's function to issue errors instead of warnings? Or introduce an enumeration instead of the current parameter? On a side note, it's really hard for me to understand why the failure of decrypting a key can be anything else than an error. However, since I don't want to introduce bugs into existing code, my proposal is to change the signature in a non-breaking way.

**Comment by nisdas** [comment]
@rkapka can you clarify what warnings you are seeing ? There should be no warning/error when decrypting the keystore unless the password is wrong. Also unless its necessary it would be better not to change the method arguments for the keystore. 

Also this will not work 
> Even though I am able to run the command using GoLand's Bazel debugging, I cannot run it via prysm.sh. I get this meesage: No help topic for 'merge'. I probably didn't register the new command somewhere. Can anyone help me?

You need to use bazel to build,run and test the project, the script downloads the tagged binaries, which are released separately.

**Comment by rkapka** [comment]
I am talking precisely about the scenario where the password is wrong. It is currently not possible to handle such a case because the library issues a warning internally and does not return any value that can be inspected.

**Pull request closed without merging**
