### PR TITLE
Deprecate `--interop-genesis-state`

### PR DESCRIPTION
**Pull request by rkapka**
**What type of PR is this?**

Cleanup

**What does this PR do? Why is it needed?**

The flag `--interop-genesis-state` does not work. Running interop with this flag results in the following error:

```
Deposit contract: 0x4242424242424242424242424242424242424242
could not get genesis block root: OriginGenesisRoot: not found in db
```

Running interop with `--genesis-state` works properly and this is the flag that should be used moving forward.

### CODE REVIEW

**Comment by kasey** [comment]
I think the pattern for deprecation is deleting the flag from it's home in `cmd/beacon-chain` and adding a new no-op flag with a deprecation warning here: ./config/features/deprecated_flags.go

Since we're close to a major version breaking change opportunity, and this is an easy removal to justify given the normal genesis state flag works, I would suggest we go ahead and also remove the code that currently uses `InteropGenesisStateFlag`. cc @terencechain as he I think he does a lot with interop and might know if there are things that could break from this, and @rauljordan to check if his interop docker stuff uses this flag.

**Comment by rkapka** [comment]
> I think the pattern for deprecation is deleting the flag from it's home in cmd/beacon-chain and adding a new no-op flag with a deprecation warning here: ./config/features/deprecated_flags.go

Ah yes, I forgot about this. Also I agree that maybe we should just remove this all together instead of deprecating.

**Comment by nisdas** [comment]
We can possibly split the removal of code that uses `InteropGenesisStateFlag` into another PR. @rkapka we prob should follow our pattern for flag deprecation in this PR, since we will probably be having another release until v4

**Review by terencechain — APPROVED** [review]
Nice removal indeed but we need to fix the tests

**Review by nisdas — APPROVED** [review]

**Pull request merged**
