### PR TITLE
Light client sync protocol

### PR DESCRIPTION
**Pull request by 7AC**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

Implements the Altair spec logic defined in this version:

https://github.com/ethereum/consensus-specs/tree/208da34ac4e75337baf79adebf036ab595e39f15/specs/altair/light-client

It also implements the relevant endpoints specified at https://github.com/ethereum/beacon-APIs

**Which issues(s) does this PR fix?**

Partially addresses https://github.com/prysmaticlabs/prysm/issues/11571

**Other notes for review**

We tested externally by running a node with this code, fetching light client updates from it and calling `Store.ProcessUpdate()` with it.

### CODE REVIEW

**Comment by claravanstaden** [comment]
Hey @7AC! Thanks for taking on this work. 😄 Any idea when it might be completed?

**Comment by 7AC** [comment]
> Hey @7AC! Thanks for taking on this work. 😄 Any idea when it might be completed?

Hey @claravanstaden, we're already using it in our chain as a library so from our point of view is basically done. We have tests on our end, the main reason it's still marked draft is I assume the Prysm folks will want to see some tests here too. We're waiting to hear their feedback before making any more changes.

**Comment by claravanstaden** [comment]
@7AC Thanks for the feedback! I'll keep an eye on this, would be awesome to get merged soon. 😄

**Comment by rkapka** [comment]
Hi @7AC! We really appreciate your contribution. I will review your code this week.

**Comment by rkapka** [comment]
Hi @7AC

Firstly, thank you for this amazing PR! Light client support has been on our todo list for a long time, but we never had the capacity to actually begin implementing it. I am very happy that you decided to tackle this.

Because we value code quality very much in our project, I don't see an option to review and merge everything at once. We can keep this PR as a reference, but you will have to open smaller-scoped PRs that can be properly reviewed.

I also have a message from one of developer from Nimbus about typical challenges that arise when supporting light client. It would be great if you could go through this list and think about each of these items.
> The typical challenges are:
– You have to think of the capella/deneb stuff as overlays on top of a copy of the altair spec.
– Your SSZ library needs support to obtain single-branch merkle proof by GeneralizedIndex. uint64 index is sufficient
– To answer requests, you will have to obtain merkle proof for historic BeaconState. This can be quite challenging, so Lodestar/Nimbus use a caching strategy where we persist those proofs on an ongoing basis so that we don't have to recompute them when requested. That works quite well. Database size discussed here: https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/beacon_chain_db_light_client.nim
– Once you have the proofs, next you need to link it up with block processing, to keep track of the best_update per sync committee period. there needs to be a way to mark updates ineligible that are not currently selected by fork choice, but on a reorg it becomes eligible again. this is mostly relevant on sync committee period boundaries.
– Also keep in mind, that there may be networks where the sync committee period boundary does not align with the fork schedule, so the database should be flexible enough to support that.
– Once you have the data, there are two network interfaces. libp2p and REST. Both have a push component, and a req/resp component.
– For libp2p, req/resp follows ForkDigest context from altair: https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/p2p-interface.md#forkdigest-context
– For libp2p, gossip encodes ForkDigest into the topic: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md#topics-and-messages
– For REST, req/resp supports both SSZ and JSON. There is a HTTP header to indicate fork digest: https://github.com/ethereum/beacon-APIs/tree/master/apis/beacon/light_client — on JSON, there is an additional version field
– For REST, HTTP SSE only supports JSON: https://github.com/ethereum/beacon-APIs/blob/master/apis/eventstream/index.yaml#L84

Having said all that, what we could start with is a list of functionalities that this PR can be broken into. If you agree with this, could you open a tracking issue in the repo where we can follow on the progress made?

Thanks a lot!

**Comment by 7AC** [comment]
@rkapka will do! Thanks for the pointers!

**Comment by rkapka** [comment]
> @rkapka will do! Thanks for the pointers!

Hi @7AC , is this something you plan on doing anytime soon? If you don't have time, then I can try opening PRs myself.

**Comment by rkapka** [comment]
Hi @qinlz2 , any update on this?

**Comment by qinlz2** [comment]
> 

Thanks for checking.  Sorry, I didn't get a chance to do this yet.    Will update you later (shouldn't be a hard task, but just tied with some other things.  We had an IBC Summit last Friday).

**Pull request merged**
