### PR TITLE
Experimental prototype of Apple M1 processor support

### PR DESCRIPTION
**Pull request by leolara**
**What type of PR is this?**

Technical support

**What does this PR do? Why is it needed?**

Adds support for Apple M1 processor

**Which issues(s) does this PR fix?**

I don't think issue is created, is it?

**Other notes for review**

DO NOT MERGE, WIP

 + Upgrades go to 1.17.6
 
- [X] FIXED: Currently disabled nogo, as new errors show up that weren't there before, needs investigation
- [X] FIXED: Not sure herumi is supported correctly
- [X] SEPARATE ISSUE: Didn't test cross compilation yet, it probably will need more work to make cross compilation work (https://github.com/prysmaticlabs/prysm/issues/10257)

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Could you add the nogo errors to the PR description or a comment here? I wonder if it has to do with updating go to 1.17 or has to do with darwin arm64. 

If it's go 1.17, then we can work on that in another PR in parallel.

**Comment by leolara** [comment]
> Could you add the nogo errors to the PR description or a comment here? I wonder if it has to do with updating go to 1.17 or has to do with darwin arm64.
> 
> If it's go 1.17, then we can work on that in another PR in parallel.

@prestonvanloon so now I do not get the errors, perhaps I had to clean the bazel cache or something, I am new to bazel :-)

The question now is if we leave the cross compilation for another task, which makes sense in my opinion

**Comment by leolara** [comment]
This is ready to review @kasey @nisdas @uncdr please review, this is about developers support

**Comment by rauljordan** [comment]
--- FAIL: TestMinimal_Altair_Forkchoice/filtered_block_tree (5.61s)
--
  | assertions.go:49: runner.go:149 Values are not equal, want: [32]uint8{0xff, 0x5, 0x65, 0xc0, 0x92, 0x13, 0x7a, 0x44, 0x8f, 0x9, 0x54, 0x79, 0xb1, 0xd3, 0xf7, 0x3c, 0x30, 0x7a, 0x3a, 0x59, 0x35, 0x7a, 0xa9, 0x83, 0xe9, 0xa9, 0xf1, 0xc1, 0xa2, 0x1a, 0x3b, 0xca}, got: [32]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, diff: modified: [0] = 0x0
  | modified: [10] = 0x0

 is failing

**Comment by prestonvanloon** [comment]
> ## --- FAIL: TestMinimal_Altair_Forkchoice/filtered_block_tree (5.61s)
>   | assertions.go:49: runner.go:149 Values are not equal, want: [32]uint8{0xff, 0x5, 0x65, 0xc0, 0x92, 0x13, 0x7a, 0x44, 0x8f, 0x9, 0x54, 0x79, 0xb1, 0xd3, 0xf7, 0x3c, 0x30, 0x7a, 0x3a, 0x59, 0x35, 0x7a, 0xa9, 0x83, 0xe9, 0xa9, 0xf1, 0xc1, 0xa2, 0x1a, 0x3b, 0xca}, got: [32]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, diff: modified: [0] = 0x0   | modified: [10] = 0x0
> 
> is failing

This is an unrelated flake

**Review by rauljordan — APPROVED** [review]

**Comment by james-prysm** [comment]
saw this small thing but it built well

INFO: From BazelWorkspaceStatusAction stable-status.txt:
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

**Review by prestonvanloon — APPROVED** [review]

**Review by james-prysm — APPROVED** [review]

**Review by prestonvanloon — APPROVED** [review]

**Comment by prestonvanloon** [comment]
> saw this small thing but it built well
> 
> INFO: From BazelWorkspaceStatusAction stable-status.txt: date: illegal option -- - usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format] date: illegal option -- - usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

Filed an issue for this #10263

**Pull request merged**
