### PR TITLE
Update cloudflare/roughtime dependency for ecosystem update

### PR DESCRIPTION
**Pull request by tannerryan**
**What type of PR is this?**

Other

**What does this PR do? Why is it needed?**

Updates the cloudflare/roughtime dependency. The Roughtime server ecosystem list has been updated.

**Which issues(s) does this PR fix?**

https://github.com/prysmaticlabs/prysm/issues/7223

**Other notes for review**

Not applicable.

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Looks like this doesn't build.

com_github_cloudflare_roughtime/mjd/mjd_linux.go:17:5: undefined: unix.TIME_OOP

**Comment by tannerryan** [comment]
The dependency has switched to platform specific code which will fail with CGO enabled. I will see if I can get the dependency fixed.

**Comment by tannerryan** [comment]
I originally thought it was an issue with CGO but it's not. The package now contains build constraints via `golang.org/x/sys/unix`.

I believe this is the same issue as https://github.com/bazelbuild/rules_go/issues/1215 but I do not know how to go about implementing the required changes.

**Comment by nisdas** [comment]
Hey @tannerryan thanks for opening this PR ! However as of #7299, we wont be using roughtime for the timebeing in Prysm, the reasons for discontinuing it are stated in the PR. It might be added back in the future once roughtime spec is standardized.

**Pull request closed without merging**
