### PR TITLE
Fix Event stream with carriage return support

### LINKED ISSUE #13730: Fully supporting Event stream standards
# 💎 Issue

This issue is to track a TODO item from PR: https://github.com/prysmaticlabs/prysm/pull/13563

in the PR we use a simple scanner to process event stream data which can handle `/n/r` or `/n` but not `/r` alone therefore not adhering to the standards defined in https://html.spec.whatwg.org/multipage/server-sent-events.html#the-eventsource-interface on the beacon api https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Events
This simple implementation can be used for now as our events endpoint is not fully mainnet ready at the time of this issue. Further improvements and full use of the events endpoint may be needed and can be re-evaluated then.

### PR DESCRIPTION
**Pull request by samuel-videau**
**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**

Add supports to `\r` as a separator while processing event streams, and therefore adhering to https://html.spec.whatwg.org/multipage/server-sent-events.html#the-eventsource-interface

**Which issues(s) does this PR fix?**

Fixes #13730

**Other notes for review**

The utility function added is just a slight modification of the ScanLines function in scan.go

### CODE REVIEW

**Comment by james-prysm** [comment]
Thanks for the submission,

looks like there is a lint issue  api/client/event/utils.go:36: File is not `gofmt`-ed with `-s`

**Comment by samuel-videau** [comment]
My bad, should be good now!

**Comment by james-prysm** [comment]
looks like there are some linter rule issues ( bazel file)
please use `bazel run //:gazelle -- fix`

**Comment by samuel-videau** [comment]
> looks like there are some linter rule issues ( bazel file) please use `bazel run //:gazelle -- fix`

Ah that's a shame sorry for that, should be good now

**Review by james-prysm — APPROVED** [review]
I think the implementation looks good to me, thanks for this contribution

**Pull request merged**
