### PR TITLE
WIP: Save blocks in goroutines

### PR DESCRIPTION
**Pull request by prestonvanloon**
Also reverts protobuf update. I was having build failures that the CI hasn't experienced yet since it hasn't been restarted. 

I was getting ~15blk/s on initial sync, this PR was getting ~20blk/s~ 26blk/s on initial sync.

Will follow up with more in memory caching

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Marking as WIP because i'm nervous about some test flaky-ness. Will confirm tmrw before accepting a merge.

**Comment by prestonvanloon** [comment]
To reduce test flakes, i'll add a `.Flush()` method to the database which will wait for any goroutines to resolve rather than waiting some arbitrary amount of time.

**Comment by rauljordan** [comment]
Still relevant @prestonvanloon ?

**Comment by prestonvanloon** [comment]
Yes, just haven’t had a moment prioritize it.

**Pull request closed without merging**
