### PR TITLE
Increase validator client startup proposer settings deadline

### LINKED ISSUE #12527: Validator client fails to update proposer settings because of bn latency with high amount of keys
# 💎 Issue

### Background

Starting the validator client fails when there are enough keys and enough latency to the beacon node to reach the 12 seconds timeout while updating proposer settings

### Description

We have a vc with failover beacon nodes, one of them is in another datacenter and there are 1k (mostly pending) keys configured. When the validator client tries to start with the failover node that has 10ms latency (vs 0.5ms of the primary) it fails after 12 seconds with:

```json
{"time":"2023-06-13T22:50:58Z","level":"info","msg":"Validator client started with provided proposer settings that sets options such as fee recipient and will periodically update the beacon node and custom builder (if --enable-builder)","prefix":"validator"}
// more validatorIndex requests
{"time":"2023-06-13T22:51:10Z","backend":null,"duration":10916936,"level":"debug","method":"/ethereum.eth.v1alpha1.BeaconNodeValidator/ValidatorIndex","msg":"gRPC request finished."}
{"time":"2023-06-13T22:51:10Z","error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"fatal","msg":"Failed to update proposer settings","prefix":"validator"}
```

while with the primary one it starts fine after 3-4 seconds:

```json
{"time":"2023-06-13T22:51:35Z","level":"debug","msg":"Prepare proposer request did not success with all pubkeys","prefix":"validator","pubkeysCount":1000,"reqCount":31}
```

It seems that the [loop](https://github.com/prysmaticlabs/prysm/blob/develop/validator/client/validator.go#L1018-L1034) that gets the validator indexes calls the beacon node sequentially. so if there's a 10ms delay and 1k keys that's already 10 seconds (without counting for the actual time taken to process the request).

What could be a possible solution? Doing the index requests in parallel? Making the 12 seconds deadline adjustable? Or is 10ms/1k keys too much?

### PR DESCRIPTION
**Pull request by 0xalex88**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

This PR increases from 12 seconds to 5 minutes the deadline to push proposer settings during the startup of the validator client.

**Which issues(s) does this PR fix?**

Fixes #12527

**Other notes for review**

I've set it to 5 minutes instead of the initially proposed 2 just to give some extra time in case of higher latency or slower beacon node (happy to set it to 2 if you think this is too much).

I've removed the test `TestUpdateProposerSettingsAt_EpochEndExceeded` which was passing because of the "deadline exceeded" error during startup, not at epoch end (the slot sent in `ticker <- slot` was the second from the last so it wasn't triggering the periodical push that only happens on first slot of the epoch).

Let me know if you prefer to restore the test and set a 5 minutes timeout (which can possibly slow down tests, and it'll still test the startup deadline).
If we want to actually test the epoch start->end deadline it would probably be possible to set a quick `ProposerSettingWait` at first to make the startup pass, then use a custom beaconConfig with fast slots, send the first slot of the epoch and wait for the deadline exceeded error.

### CODE REVIEW

**Comment by 0xalex88** [comment]
I think this would be a possible test to test the end epoch deadline exceeded:
```go
func TestUpdateProposerSettingsAt_EpochEndExceeded(t *testing.T) {
	v := &testutil.FakeValidator{Km: &mockKeymanager{accountsChangedFeed: &event.Feed{}}, ProposerSettingWait: 1 * time.Second}
	v.SetProposerSettings(&validatorserviceconfig.ProposerSettings{
		DefaultConfig: &validatorserviceconfig.ProposerOption{
			FeeRecipientConfig: &validatorserviceconfig.FeeRecipientConfig{
				FeeRecipient: common.HexToAddress("0x046Fb65722E7b2455012BFEBf6177F1D2e9738D9"),
			},
		},
	})
	ctx, cancel := context.WithCancel(context.Background())
	hook := logTest.NewGlobal()
	config := params.BeaconConfig()
	config.SecondsPerSlot = 1
	params.OverrideBeaconConfig(config)
	ticker := make(chan primitives.Slot)
	v.NextSlotRet = ticker
	go func() {
		ticker <- primitives.Slot(params.BeaconConfig().SlotsPerEpoch)
		v.ProposerSettingWait = time.Duration(params.BeaconConfig().SlotsPerEpoch+1) * time.Second
		ticker <- primitives.Slot(params.BeaconConfig().SlotsPerEpoch + 1)
		time.Sleep(v.ProposerSettingWait)
		cancel()
	}()

	run(ctx, v)
	// can't test "Failed to update proposer settings" because of log.fatal
	assert.LogsContain(t, hook, "deadline exceeded")
}
```

ProposerSettingWait starts at 1 to just pass the startup push, the a non first-epoch-slot is passed to the channel just to make sure the startup is done, it then changes the ProposerSettingWait to 33 seconds (32 slots + 1 seconds since the SecondsPerSlot is set to 1), then after the epoch ends we get the deadline exceeded

**Comment by james-prysm** [comment]
circling back on this now

**Comment by james-prysm** [comment]
Apologies for being so late on this.
I added a few changes in https://github.com/prysmaticlabs/prysm/pull/12456 that will improve this situation 
1. the periodic calls will happen at the middle of each epoch instead of start of each epoch
2. the validator registration is used to save to the database on the beacon node side, but I made the validator registration use a cache by default, this means it won't use the db writes and only store in memory on the beacon node side ( fee recipients will still be stored in db on beacon node). Hopefully, this reduces some of the pain points

going back to this PR I thought about it and let's include your PR now that we have those settings. I'll open something else as I think about an unsafe skipping of calling proposer settings on startup if that's still needed.

**Review by james-prysm — APPROVED** [review]
Approving with comments above.

**Comment by 0xalex88** [comment]
Thank you for taking the time to look at this!

**Pull request merged**
