### PR TITLE
[WIP] Using fixed length byte arrays in protobuf 

### PR DESCRIPTION
**Pull request by prestonvanloon**
TODO(preston): add description

### CODE REVIEW

**Comment by nisdas** [comment]
@prestonvanloon can you switch this pr to the spec-v0.6 branch ?

**Comment by prestonvanloon** [comment]
@nisdas. No, I will do a follow up in the spec-v0.6 branch.

Plan:
- Sync master -> spec-v0.6
- Fix this up
- Sync master -> spec-v0.6
- Fix everything this PR breaks in spec-v0.6

**Comment by prestonvanloon** [comment]
This should land tomorrow. It is in my top priorities

**Comment by nisdas** [comment]
Great, sounds good to me. As long as we have this in the spec-v0.6 branch too

**Comment by prestonvanloon** [comment]
Ran into some major blockers with gogoprotobuf custom types. proto.Clone not working was a deal breaker!

Closing this in favor of handling the underlying issue at the encoding library level. 
See: https://github.com/prysmaticlabs/go-ssz/issues/9

**Pull request closed without merging**
