### PR TITLE
Remove canonical check when prunning attestations from pool

### LINKED ISSUE #11934: change signature of `pruneCanonicalAttsFromPool`
Currently the function `pruneCanonicalAttsFromPool` is called only from `onBlock` at a point where the head root and the incoming block root are known. the only way for the block to be canonical is if these two roots are equal. There  is no need for the canonical check being performed withing the function `pruneCanonicalAttsFromPool`.

### PR DESCRIPTION
**Pull request by potuz**
Fixes #11934

### CODE REVIEW

**Review by terencechain — CHANGES_REQUESTED** [review]
We already have a PR for this: https://github.com/prysmaticlabs/prysm/pull/11771

Why are we opening another one?

**Comment by potuz** [comment]
> We already have a PR for this: #11771
> 
> Why are we opening another one?

Because this avoids completely the extra check in the helper. The signature of `pruneCannonicalAttsFromPool` is simply wrong.

**Comment by terencechain** [comment]
> > We already have a PR for this: #11771
> > Why are we opening another one?
> 
> Because this avoids completely the extra check in the helper. The signature of `pruneCannonicalAttsFromPool` is simply wrong.

Let's fix this in https://github.com/prysmaticlabs/prysm/pull/11771. I think the correct procedure would have bene review on top of that rather than over rides it (completely). The only review would have been rename the function name

**Comment by potuz** [comment]
> > > We already have a PR for this: #11771
> > > Why are we opening another one?
> > 
> > 
> > Because this avoids completely the extra check in the helper. The signature of `pruneCannonicalAttsFromPool` is simply wrong.
> 
> Let's fix this in #11771. I think the correct procedure would have bene review on top of that rather than over rides it (completely). The only review would have been rename the function name

sure, I can close this, but notice that is not only function rename but also removing the extra check and parameter.

**Pull request closed without merging**
