### PR TITLE
Refactor validator subnet subscriptions to be non-blocking

### LINKED ISSUE #8194: Redundant request for getting duties for the next epoch
https://github.com/prysmaticlabs/prysm/blob/4c6e0c5f4656b7f0b6a7df065d4ec0a3b802d4e0/validator/client/validator.go#L381

No needed to send one more request for getting duties of the next epoch. It is possible to get the same data from the first response `resp.GetNextEpochDuties()` without sending one more RPC request.

### PR DESCRIPTION
**Pull request by prestonvanloon**
**What type of PR is this?**

Other

**What does this PR do? Why is it needed?**

See these hackmd notes [link](https://hackmd.io/MkAtcRTfRWmN67V0EmXCRA?view). 
This PR implements suggestion 1 with some light modifications to fix #8194. 

**Which issues(s) does this PR fix?**

Fixes #8194

**Other notes for review**

Tested in Prymont with ~200 active validator keys. 

Credit to @KaanKC for their work in PR #8204

### CODE REVIEW

**Review by terencechain — DISMISSED** [review]

**Review by terencechain — APPROVED** [review]

**Comment by prestonvanloon** [comment]
Failing E2E, similar to #8204. I'm wondering if the next epoch duties are implemented correctly. 
Fundamentally, there should be no difference in using resp.NextEpochDuties vs asking for duties again for `epoch+1`.

**Comment by prestonvanloon** [comment]
This fails e2e practically 100% of the time. Investigating soon.

**Comment by prestonvanloon** [comment]
Update: e2e passes when disabling proposer cache. Investigating...

**Comment by prestonvanloon** [comment]
Removing these lines of code make e2e pass again: https://github.com/prysmaticlabs/prysm/blob/9afc9d92d91a56904e618bba59dc8da895d99c80/beacon-chain/blockchain/process_block.go#L378-L380

**Comment by prestonvanloon** [comment]
E2E fixed since #8424. Thanks @terencechain!

This is ready for final review.

**Review by terencechain — APPROVED** [review]

**Review by nisdas — APPROVED** [review]

**Pull request merged**
