### PR TITLE
WIP phase2 wasm executeCode improvement

### PR DESCRIPTION
**Pull request by skillful-alex**
Changes:
1) Added imports for the Scout project call wasm code 
2) Changed the style of the wasm package from the executable program to normal package with unit tests
3) Added testing of executeCode method with tests definition in yaml file
4) Added test with call the wasm of Scout project

Next steps:
* Implement read/write memory of wasm instance (Now executeCode alway return prestate)
* Add more tests for the executeCode method (it seems that a stir has begun in the Scout project) or we have to write the wasm code independently

### CODE REVIEW

**Comment by skillful-alex** [comment]
due to a change in the logic of the PR, created https://github.com/prysmaticlabs/prysm/pull/4229

**Comment by rauljordan** [comment]
Hi @skillful-alex thanks for this - it seems there are some lint failures because CI expects the TODO formatting to be of the form: `TODO(#ISSUENUMBER):` instead of just `TODO:`

**Comment by rauljordan** [comment]
Looks like still one more @skillful-alex 



wasm/execute_code.go:38:	//TODO Get post_state_root and deposits

**Comment by rauljordan** [comment]
There are still some failures, sorry for the back and forth. Could you try running gometalinter locally to see if any more pop up before pushing?

```
wasm/main.go:81:1: exported function ProcessShardBlock should have comment or be unexported
--
  | wasm/main.go:81:85: exported func ProcessShardBlock returns unexported type *wasm.shardState, which can be annoying to use
  | wasm/envs/naive-ee/main.go:6:1: comment on exported function Sum should be of the form "Sum ..."
  | Found 3 lint suggestions; failing.
```

**Comment by skillful-alex** [comment]
Did not create a issue and marked all TODO as TODO(# 0). In the current state, questions only create garbage because most of the code needs to be rewritten.

**Comment by rauljordan** [comment]
No prob, the issue number 0 is fine for now. Can we resolve the last few lint issues? Than we can merge

**Pull request merged**
