### PR TITLE
Extract generic ssz types from p2p package to sszutil/types

### PR DESCRIPTION
**Pull request by pinglamb**
**What type of PR is this?**

> Other

**What does this PR do? Why is it needed?**

Follow up of discussion here: https://github.com/prysmaticlabs/prysm/pull/8257#discussion_r556770945. `p2p/types` defined some basic `SSZType` and are extracted to `sszutil/types` as they are not specific to `p2p`.

There is a import cycle between `testutil` and `sszutil` causing some packages fail to build so the type definition is moved into `sszutil/types` instead of under `sszutil`.

**Which issues(s) does this PR fix?**

**Other notes for review**

As @nisdas [suggested](https://github.com/prysmaticlabs/prysm/pull/8464#pullrequestreview-592825149), we can further move these to https://github.com/prysmaticlabs/eth2-types repo. I think we can merge this first and address that in separate PRs.

### CODE REVIEW

**Review by rauljordan — DISMISSED** [review]

**Comment by rauljordan** [comment]
hey @pinglamb needs to run `bazel run //:gazelle -- fix`

```
compilepkg: missing strict dependencies:
--
  | /root/.cache/bazel/_bazel_root/9b863db945037dda70605b5529ac0f05/sandbox/processwrapper-sandbox/7848/execroot/prysm/shared/params/loader_test.go: import of "github.com/prysmaticlabs/prysm/shared/testutil/assert"
  | /root/.cache/bazel/_bazel_root/9b863db945037dda70605b5529ac0f05/sandbox/processwrapper-sandbox/7848/execroot/prysm/shared/params/loader_test.go: import of "github.com/prysmaticlabs/prysm/shared/testutil/require"
  | No dependencies were provided.
```

**Comment by pinglamb** [comment]
@rauljordan I also spotted the issue and there is no change after running `bazel run //:gazelle -- fix`. When I run `bazelisk test //shared/params:go_default_test --sandbox_debug` locally, it results with the same compile error and I can't see `-arc` the `testutil/assert` and `testutil/require` in the command.

I got a similar error in the `sszutil` package when I try to change `package sszutil_test` to `package sszutil`. I am not sure what the problem is :(

**Comment by rkapka** [comment]
You can try adding the required import manually into the bazel file. It is located in the same folder as `sparse_merkle_test.go`.

**Review by nisdas — CHANGES_REQUESTED** [review]
This might be better suited to be transferred over to 
https://github.com/prysmaticlabs/eth2-types 

We have a custom types package over there which seems like the more appropriate place to keep types such as these.

**Comment by pinglamb** [comment]
@rkapka It seems that the `shared/trieutil` failed to build because `shared/params` failed to build. The `deps` in `shared/params/BUILD.bazel` did contain the imports for `github.com/prysmaticlabs/prysm/shared/testutil/assert` and `github.com/prysmaticlabs/prysm/shared/testutil/require` after running `bazel run //:gazelle -- fix`: https://github.com/pinglamb/prysm/blob/refactor-basic-ssz-types/shared/params/BUILD.bazel#L48. But I can't see it in the sandbox command after running `bazelisk test //shared/params:go_default_test` with the `--sandbox_debug` flag. So weird.

**Comment by pinglamb** [comment]
It seems that the reason for this is because `shared/testutil/assertions` has a dependency on `shared/sszutil` causing `bazel` not to include `shared/testutil/assert` and `shared/testutil/require` when it runs the sandbox command: https://github.com/prysmaticlabs/prysm/blob/develop/shared/testutil/assertions/BUILD.bazel#L10. After I temporarily remove the dependency (and remove the `DeepSSZEqual` and `DeepNotSSZEqual`), the build works again.

I think it is better for `shared/testutil/assertions` not to depend on other project packages as it is likely to be used by everyone. What do you guys think?

**Comment by pinglamb** [comment]
Updated description to reflect how to fix the build:

```
There is a import cycle between testutil and sszutil causing some packages fail to build so the type definition is moved into sszutil/types instead of under sszutil.
```

**Comment by rauljordan** [comment]
PTAL @nisdas

**Comment by pinglamb** [comment]
Close this for now as we are moving the types to https://github.com/prysmaticlabs/eth2-types instead

**Pull request closed without merging**
