### PR TITLE
Block operations spec tests

### PR DESCRIPTION
**Pull request by terencechain**
~Blocked by https://github.com/prysmaticlabs/go-ssz/pull/41~

Current status: 

|                                   |                         |
|----------------------------|----------------------|
| attestation | **Pass** |
| attester_slashing | **Pass** |
| block_header | **Pass** |
| deposit | **Conditional Pass**, see #2857 |
| proposer_slashing | **Pass**  |
| transfer | **Pass** |
| voluntary_exit | **Pass**  |

https://github.com/ethereum/eth2.0-specs/tree/dev/specs/test_formats/operations

### CODE REVIEW

**Comment by terencechain** [comment]
Update:
@nisdas taking deposit
@prestonvanloon taking attestation

**Comment by terencechain** [comment]
I'm going to take `voluntary_exit` now

**Comment by prestonvanloon** [comment]
I'll take `block_header`

**Comment by terencechain** [comment]
taking `transfer`

**Comment by terencechain** [comment]
Blocked. Pending update to the test yaml:

Screen Shot 2019-06-29 at 2 40 51 PM

**Comment by prestonvanloon** [comment]
2 spec test targets failing. 

```
//beacon-chain/core/blocks/spectest:go_default_test                      FAILED in 174.8s
//beacon-chain/core/state/spectest:go_default_test                       FAILED in 96.9s
```

**Comment by prestonvanloon** [comment]
Latest update: trying to investigate where the regression in processing the block header. There is currently a failure where the latest block header signing root is not matching the block's parent root. This is either a problem in our ssz implementation of signing root, misconfigured proto tags, bad data from the spec test generator, or a bug in our implementation of processing block headers.

**Comment by prestonvanloon** [comment]
This is ready for review. All tests passing

**Pull request merged**
