### PR TITLE
Merge ascii art banner

### LINKED ISSUE #10469: Help wanted: merge transition banner art
Looking for help to make an ASCII style art banner appear at the point of the merge transition. 

The banner should emit at the end of this function: https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/blockchain/pow_block.go#L40

Requirements:
- The official merge mascot Panda(s) should appear 🐼 
- It doesn't break run time
- Optional color but must not break existing user settings 

References:
https://twitter.com/terencechain/status/1506346434370494465
https://twitter.com/EthDreamer/status/1506372002512314376

### PR DESCRIPTION
**Pull request by Blauyourmind**
**What type of PR is this?**
 Other

**What does this PR do? Why is it needed?**

Add an ASCII art banner to appear after the merge is complete. 

**Which issues(s) does this PR fix?**

Fixes #10469

**Other notes for review**

### CODE REVIEW

**Review by rauljordan — APPROVED** [review]

**Comment by rauljordan** [comment]
Thanks for the awesome art!!

**Review by prestonvanloon — DISMISSED** [review]
Looks good to me! 

It might not work well on small screens / terminals with line wrapping, but it's just for fun anyway :)

**Review by prestonvanloon — APPROVED** [review]

**Comment by Blauyourmind** [comment]
Is there a code format I am missing here with the check failing?

**Comment by terencechain** [comment]
Screen Shot 2022-06-08 at 12 09 17 PM
This looked great today! Thanks @Blauyourmind

**Comment by Blauyourmind** [comment]
Wow so cool!!!!

**Review by terencechain — DISMISSED** [review]

**Review by rkapka — APPROVED** [review]

**Pull request merged**
