### PR TITLE
Use fieldparams for BLS public key

### PR DESCRIPTION
**Pull request by terencechain**
Use `fieldparams.BLSPubKey` instead of magic number `48` across the codebase

### CODE REVIEW

**Comment by rkapka** [comment]
Should the package still be called `fieldparams`? The original usage was beacon state fields, but it seemed to expand lately.

**Comment by terencechain** [comment]
> I don't think the package should still be called `fieldparams`. The original usage was beacon state fields, but it seemed to expand lately.

`fieldparams` is still correct, it's not `state_fieldparams`, but I'm happy to change it if anyone has a better suggestion

**Review by rkapka — CHANGES_REQUESTED** [review]

**Comment by terencechain** [comment]
@rkapka thanks for being diligent, those are definitely my find/replace misses

**Review by rkapka — APPROVED** [review]

**Comment by terencechain** [comment]
@rkapka Had to resolve conflicts. Sorry to bug you again

**Review by prestonvanloon — APPROVED** [review]

**Pull request merged**
