### PR TITLE
Update go-libp2p to v0.22.0 and update import paths

### PR DESCRIPTION
**Pull request by MarcoPolo**
**What type of PR is this?**
Hey folks! go-libp2p maintainer over here. I know the latest v0.22.0 monorepo changes are a bit annoying, so I hope this helps.

This updates the import paths for go-libp2p core. With the monorepo consolidation in v0.22.0 the old go-libp2p-core has moved into go-libp2p/core. This requires updating the import paths throughout the codebase, as well as getting rid of the `go-libp2p-core` dependency. More info here: https://github.com/libp2p/go-libp2p/releases/tag/v0.22.0

> Other

**What does this PR do? Why is it needed?**
Updates the go-libp2p dependency. Having an up to date dep here helps us quickly ship any fixes to any issues you encounter.

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**
This PR targets https://github.com/prysmaticlabs/prysm/pull/11309. 

If you'd like to recreate this patch a simple find/replace will do it.

### CODE REVIEW

**Comment by MarcoPolo** [comment]
cc @prestonvanloon since this targetting your PR :)

**Comment by prestonvanloon** [comment]
Hi @MarcoPolo Thanks so much for the PR. This update has been particularly difficult indeed. I am thankful for your contribution and I was wondering if you would be so willing as to fix the tests builds as well? Try building all of the tests like `go test -run=^$ ` and you will see some fail to build. 

If you could kindly resolve those issues, then I can accept this merge to my branch and push forward on that update. In any case, thanks so much. This is a huge help!

**Comment by MarcoPolo** [comment]
Ah yes, I forgot to update the `go-libp2p-peerstore` dep as well. Just made that change and the tests all build.

**Review by prestonvanloon — APPROVED** [review]
Amazing, thank you so much!!

**Pull request merged**
