### PR TITLE
Docker rpc

### PR DESCRIPTION
**Pull request by mkinney**
[Part of] #3817

---

# Description
docker needs to have the name of the docker before the image otherwise it will error. Also, add info on how to start with gRPC enabled via docker command. Fix the help syntax in the interop script as well as add rpc option there, too.

Update documentation on how to start with gRPC.

Notes:
1) Not sure how to test the interop test script.
2) I can see port 7000 open from docker host (my mac), but I still get:

`curl: (52) Empty reply from server`

when I run:

`curl http://127.0.0.1:7000/eth/v1alpha1/node/syncing`

### CODE REVIEW

**Comment by nisdas** [comment]
You have conflicts to fix

**Comment by mkinney** [comment]
No, this still does not work for me.

I just re-tested. I spun up a new Digital Ocean instance, installed docker ce, ran docker command to spin up new beacon chain, saw that it opens up port 7000, but I don't get the response I would expect.

```
root@d2:~# docker run -v $HOME/prysm-data:/data -p 4000:4000 -p 7000:7000 \
>   --name beacon-node \
>   gcr.io/prysmaticlabs/prysm/beacon-chain:latest \
>   --datadir=/data \
>   --no-genesis-delay \
>   --grpc-gateway-port=7000
Unable to find image 'gcr.io/prysmaticlabs/prysm/beacon-chain:latest' locally
latest: Pulling from prysmaticlabs/prysm/beacon-chain
e8d8785a314f: Pull complete
e005d777a298: Pull complete
308375e594da: Pull complete
Digest: sha256:f892682ed4c28a72e43991e1ec91635723d406c231db06e52bb7610455f58b94
Status: Downloaded newer image for gcr.io/prysmaticlabs/prysm/beacon-chain:latest
2019/11/06 17:26:41 maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined
time="2019-11-06 17:26:41" level=error msg="no-genesis-delay is deprecated and has no effect. Do not use this flag, it will be deleted soon." prefix=flags
time="2019-11-06 17:26:41" level=info msg="Using custom chain parameters" config=demo prefix=node
time="2019-11-06 17:26:41" level=info msg="Checking DB" database-path="/data/beaconchaindata" prefix=node
time="2019-11-06 17:26:41" level=info msg="Fetching testnet cluster address" endpoint="https://prylabs.net/contract" prefix=node
time="2019-11-06 17:26:42" level=info msg="Starting beacon node" prefix=node version="Git commit: 5a789fca4a89ae3b184c3c4fe6dba79d780b6358. Built at: 2019-11-06 16:21:30+00:00"
time="2019-11-06 17:26:42" level=info msg="Starting 9 services: [*p2p.Service *powchain.Service *operations.Service *blockchain.Service *initialsync.InitialSync *sync.RegularSync *rpc.Service *gateway.Gateway *prometheus.Service]" prefix=registry
time="2019-11-06 17:26:42" level=info msg="Waiting to reach the validator deposit threshold to start the beacon chain..." prefix=blockchain
time="2019-11-06 17:26:42" level=info msg="RPC-API listening on port" port=":4000" prefix=rpc
time="2019-11-06 17:26:42" level=warning msg="You are using an insecure gRPC connection! Provide a certificate and key to connect securely" prefix=rpc
time="2019-11-06 17:26:42" level=info msg="Starting gRPC gateway." address="127.0.0.1:7000" prefix=gateway
time="2019-11-06 17:26:42" level=info msg="Collecting metrics at endpoint" endpoint=":8080" prefix=prometheus
```

```
root@d2:~# netstat -antd | grep 7000
tcp6       0      0 :::7000                 :::*                    LISTEN
root@d2:~# curl http://127.0.0.1:7000/eth/v1alpha1/node/syncing
curl: (56) Recv failure: Connection reset by peer
root@d2:~#
root@d2:~# docker ps -a
CONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS              PORTS                                            NAMES
259a2e5c3458        gcr.io/prysmaticlabs/prysm/beacon-chain:latest   "/app/beacon-chain/i…"   3 minutes ago       Up 3 minutes        0.0.0.0:4000->4000/tcp, 0.0.0.0:7000->7000/tcp   beacon-node
root@d2:~#
```

The problem only appears to be docker related. If I run the node locally (from source on mac not using docker), it works.

But, I still cannot get it to work from docker.

Where/how are the docker images built?

**Comment by mkinney** [comment]
Is this line correct?  https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/node/node.go#L481

Should:
> 		selfAddress := fmt.Sprintf("127.0.0.1:%d", ctx.GlobalInt(flags.RPCPort.Name))

be:
>		selfAddress := fmt.Sprintf("127.0.0.1:%d", ctx.GlobalInt(flags.GRPCGatewayPort.Name))

**Comment by prestonvanloon** [comment]
@mkinney that is correct. However, I think this the gateway address should be changed to 
```go
		gatewayAddress := fmt.Sprintf("0.0.0.0:%d", gatewayPort)
```

You can test this by changing the line above and building the new docker image:

```
bazel run //beacon-chain:image
```
This will tag the image and run it in docker.

**Comment by duktig666** [comment]
I also encountered this problem. 
```
curl: (56) Recv failure: Connection reset by peer
```
version:2.1.2

docker:
```
docker run -it -v /data/eth2/.eth2:/data -v /data/eth2/eth2-ext/genesis.ssz:/genesis/genesis.ssz -p 3500:3500 -p 4000:4000 -p 13000:13000 -p 12000:12000/udp -d --name beacon-node \
  gcr.io/prysmaticlabs/prysm/beacon-chain:stable \
  --datadir=/data \
  --rpc-host=0.0.0.0 \
  --monitoring-host=0.0.0.0 \
  --http-web3provider=  \
  --genesis-state=/genesis/genesis.ssz \
  --prater
```

**Pull request merged**
