### PR TITLE
Use Scoring Parameters To Enable Global Score

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Feature Addition

**What does this PR do? Why is it needed?**

- [x] Enable Gossip Scorer With Overall Scoring Service
- [x] Replace Bad Count Checker with overall Score for a more even determination of a peer's score.
- [x] Gate With Scorer Flag for Important Methods.

**Which issues(s) does this PR fix?**

N.A

**Other notes for review**

### CODE REVIEW

**Review by farazdagi — DISMISSED** [review]
Looks great!

**Review by prestonvanloon — COMMENTED** [review]
Whats the status on this? It's getting stale

**Review by prestonvanloon — APPROVED** [review]

**Comment by nisdas** [comment]
@prestonvanloon This consistently fails e2e, I havent had time to dig in on it. Will take a look today if I get the time.

**Comment by prestonvanloon** [comment]
@nisdas thanks for the update. No urgency on this. I was just probing for info. Thanks!

**Comment by prestonvanloon** [comment]
Gentle ping on this!

**Comment by nisdas** [comment]
Will work on this tomorrow

**Review by prestonvanloon — APPROVED** [review]

**Pull request merged**
