### PR TITLE
Add working go mod files

### PR DESCRIPTION
**Pull request by anacrolix**
Adds working go.mod files for building the project. In particular prometheus must be held back to v2.1, and specific libp2p revisions must be used (until go.mod is added there).

### CODE REVIEW

**Comment by terenc3t** [comment]
hi @anacrolix, getting this error:
`go get: -t flag is a no-op when using modules`

**Comment by anacrolix** [comment]
You can remove that command completely.

**Comment by rauljordan** [comment]
Hey @anacrolix, tried this out and looks like travis still tries to do a go get even when adding the `install: true` property in the yaml. Any suggestions on how to fix this?

**Comment by prestonvanloon** [comment]
We use bazel for our production dependency management. For some tool compatibility reasons, we are using travis to run our advanced linter and coverage with dependencies fetched from head. Given that go.mod doesn't seem to work out of the box for travis, this doesn't look like a necessary change.

**Comment by anacrolix** [comment]
https://dave.cheney.net/2018/07/16/using-go-modules-with-travis-ci

**Pull request closed without merging**
