### PR TITLE
Set Fork Schedule at Node Initialization

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Feature Work

**What does this PR do? Why is it needed?**

- [x] In the event we are reading from a config yaml, this allows the node to manually setup its fork version schedule so that 
there aren't any mismatches when this is used at runtime.

**Which issues(s) does this PR fix?**

N.A

**Other notes for review**

### CODE REVIEW

**Comment by terencechain** [comment]
Can we target this to develop branch?

**Comment by rauljordan** [comment]
@terencechain it requires a few more changes from hf1 for it to work in develop as it modifies a global config. Would rather leave it in hf1 for now

**Comment by terencechain** [comment]
Another one, do we need to add this for old slasher?

**Comment by nisdas** [comment]
> Another one, do we need to add this for old slasher?

Given that the old slasher is deprecated, I don't think there is much value of adding it there.

**Comment by rauljordan** [comment]
Agreed, we no longer even ship slasher binaries

**Pull request merged**
