### PR TITLE
Add priority queue tests

### PR DESCRIPTION
**Pull request by terencechain**
Add the missing priority queue tests from https://github.com/hashicorp/vault/blob/d341378c6353a9e0f776ca024215ea11be8672df/sdk/queue/priority_queue_test.go

### CODE REVIEW

**Review by prestonvanloon — DISMISSED** [review]

**Comment by prestonvanloon** [comment]
Needs gazelle

**Comment by rauljordan** [comment]
Static analysis failing for err check

**Comment by terencechain** [comment]
> Static analysis failing for err check

Thanks for fixing!

**Review by prestonvanloon — APPROVED** [review]
I didn't review the contents of the test thoroughly. Thanks for adding these!

**Pull request merged**
