### PR TITLE
Enable slashing protection in validator by default

### LINKED ISSUE #5267: Release --protect-proposer and --protect-attester for Testnet Restart
Currently we do not require our validators to have a db to protect them against accidentally slashing themselves. This should be the default for running our validators in the next testnet restart. Although this might affect our k8s deployments as now all our validator clients will need to have a db. @prestonvanloon would this be possible to implement for our next testnet restart ?

### PR DESCRIPTION
**Pull request by prestonvanloon**
Resolves #5267

Also upgrades the warning message to error level.

### CODE REVIEW

**Comment by 0xKiwi** [comment]
Have we let this flag run on the cluster?

**Comment by prestonvanloon** [comment]
We have not. Does this need to run in prod first?

**Comment by 0xKiwi** [comment]
It doesn't, but I'd figure we should try the flag in the cluster first before making it an opt-out feature. Wdyt?

**Comment by terencechain** [comment]
Validators need to have a DB with this feature? what happens if they don't? does it panic?

**Comment by 0xKiwi** [comment]
> Validators need to have a DB with this feature? what happens if they don't? does it panic?

Defining `datadir` has been required since this feature was added.

**Comment by prestonvanloon** [comment]
OK i will try adding both of these flags in prod

**Comment by terencechain** [comment]
Ok so @prestonvanloon knows cluster needs to update if this merges into master

**Comment by prestonvanloon** [comment]
What needs to be updated?

**Comment by prestonvanloon** [comment]
This is running in prod now and has been enabled for e2e for some time. 

While we don't expect any issues here, we'll wait 1 hour to merge. (22:00 UTC)

**Comment by prestonvanloon** [comment]
No issues in prod. @0xKiwi PTAL

**Comment by 0xKiwi** [comment]
LGTM!

**Pull request merged**
