### PR TITLE
Move state interface to /shared/interface pkg

### PR DESCRIPTION
**Pull request by terencechain**
Move interface definitions in `state` pkg to `shared/interface`. Better consolidation, the state interface now lives next to block interface and more

### CODE REVIEW

**Review by prestonvanloon — COMMENTED** [review]
I am not very happy about this package `github.com/prysmaticlabs/prysm/shared/interfaces`. Being so generic and undefined means this package could become bloated and unmaintainable. Is this really the best place to put a BeaconState interface? Same goes for the other definitions in this package.

**Comment by terencechain** [comment]
> I am not very happy about this package `github.com/prysmaticlabs/prysm/shared/interfaces`. Being so generic and undefined means this package could become bloated and unmaintainable. Is this really the best place to put a BeaconState interface? Same goes for the other definitions in this package.

My motivation here is advocating state and block should be under the same pkg since they are so close to each other. Disparity raises where we define these interfaces in different locations and it looks messy in code ie. import block interface from location A and then import state interface from location B. 

I think your question is more on where we should be putting these interfaces. Ie. Closer to it's implementation or somewhere else. I would love to see more discussion on this and perhaps we can follow this up with an issue

**Comment by prestonvanloon** [comment]
> I think your question is more on where we should be putting these interfaces. Ie. Closer to it's implementation or somewhere else. I would love to see more discussion on this and perhaps we can follow this up with an issue

Yes, this is what I am saying. I would think that the BeaconState interface lives in the state package or near the protobuf generated code (if any exists). Having an application wide collection of different interfaces seems like an antipattern.

**Comment by terencechain** [comment]
> > I think your question is more on where we should be putting these interfaces. Ie. Closer to it's implementation or somewhere else. I would love to see more discussion on this and perhaps we can follow this up with an issue
> 
> Yes, this is what I am saying. I would think that the BeaconState interface lives in the state package or near the protobuf generated code (if any exists). Having an application wide collection of different interfaces seems like an antipattern.

I tend to agree and we should just fix it now. The correction actions consist of:
 - Leave state interface as it is
 - Move block interface next to the protobuf generated code
 - Move meta interface next to the protobuf generated code

**Pull request closed without merging**
