### PR TITLE
Clean Up In Memory Deposits in DB

### PR DESCRIPTION
**Pull request by nisdas**
This is a part of #3064

- [x] Moves all deposit objects into their own separate struct
- [x] Fix references and tests across the repo.

### CODE REVIEW

**Comment by prestonvanloon** [comment]
please resolve conflicts

**Comment by rauljordan** [comment]
Hey @nisdas any update on this PR? would be great to get it checked-in so that we can deprecate and remove all deposit functionality from the db package in favor of this.

**Comment by nisdas** [comment]
@rauljordan ah k, let me just clear up conflicts on this

**Comment by nisdas** [comment]
@rauljordan PTAL, fixed conflicts

**Pull request merged**
