### PR TITLE
Invert enable-eth1data-majority-vote

### PR DESCRIPTION
**Pull request by rkapka**
**What type of PR is this?**

Other/Flag Inversion

**What does this PR do? Why is it needed?**

`enable-eth1data-majority-vote` -> `disable-eth1data-majority-vote`

**Which issues(s) does this PR fix?**

Part of #6766

**Other notes for review**

N/A

### CODE REVIEW

**Comment by rkapka** [comment]
Marking this as draft for now. I will reopen the PR once we have some data about voting consistency between Prysm and other clients.

**Comment by rkapka** [comment]
Marking as blocked as this is waiting for an optimization PR related with checking if an ETH1 block exists.

**Comment by rkapka** [comment]
Unblocked by #7541

**Comment by rkapka** [comment]
Validators running against our experimental nodes seem to be handling voting pretty well. PR unblocked.

**Review by rauljordan — APPROVED** [review]

**Pull request merged**
