### PR TITLE
[Service Config Revamp] - P2P Initialization

### PR DESCRIPTION
**Pull request by rauljordan**
Part of our code health plan in #9771, this PR begins a revamp of the p2p service initialization and configuration using a functional options pattern we plan to adopt for our codebase as designed in [here](https://prysmaticlabs.notion.site/Revisiting-Prysm-Service-Configuration-Initialization-f916d12f5b234b61bae61707177d4508). This follows the pattern from #9783

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Any update on this?

**Comment by rauljordan** [comment]
Hey @prestonvanloon , ill pick this up later in the week

**Comment by prestonvanloon** [comment]
Removing myself for review so it can be out of my queue. Please add me back as reviewer when it's ready to review, thanks!

**Comment by rauljordan** [comment]
This PR is becoming unwieldy to resolve conflicts with and dangerous tests fail. It is better to start from scratch from develop, as this has changed a lot since

**Pull request closed without merging**
