### PR TITLE
Update Get Block Root function

### LINKED ISSUE #1247: Update Get Block Root function
Our [get_block_root](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/blocks/block.go#L71) helper function is obsolete. Let's update it with the spec. I'm marking it as high priority because get_block_root is used in a few places. While we moving further to implement the spec, we should fix this first : )

**Ours:**
```
   def get_block_root(state: BeaconState, slot: int) -> Hash32:
     """
     Returns the block hash at a recent ``slot``.
     """
     earliest_slot_in_array = state.slot - len(state.latest_block_roots)
     assert earliest_slot_in_array <= slot < state.slot
     return state.latest_block_roots[slot - earliest_slot_in_array]
```

**New:**
```
def get_block_root(state: BeaconState, slot: int) -> Hash32:
    """
    Returns the block root at a recent ``slot``.
    """
    assert state.slot <= slot + LATEST_BLOCK_ROOTS_LENGTH
    assert slot < state.slot
    return state.latest_block_roots[slot % LATEST_BLOCK_ROOTS_LENGTH]
```

### PR DESCRIPTION
**Pull request by JerryFireman**
TODO(you): choose "part of" or "resolves" and the associated github issue #.

Resolves #1247 

---

# Description

TODO(you): Write why you are making the changes in this pull request.
Issue #1247 requested updating Block Root function to latest spec

TODO(you): Write a summary of the changes you are making.
Updated BlockRoot specification to match new spec. UpdatedTestBlockRootAtSlot_OK and TestBlockRootAtSlot_OutOfBounds to match new spec.

TODO(you): Link anything that would be helpful or relevant to the reviewers.

### CODE REVIEW

**Comment by terenc3t** [comment]
@JerryFireman can you please fix lint and make sure the build and tests pass first?

**Comment by JerryFireman** [comment]
Thanks for the  feedback @terenc3t. I am on this.

**Comment by JerryFireman** [comment]
@terenc3t Hi Terence, I fixed lint (only issue it reports is with a go-ethereum file which I don't think has anything to do with me but please let me know if I need to address it), unit tests pass, and system builds and runs without errors using go run from the command line. If this sufficient or is there anything else I need to do before I update the PR? Thanks for your help!

**Comment by terenc3t** [comment]
Lint failed, see this error: 
block.go:78:31: error strings should not be capitalized or end with punctuation or a newline
Found 1 lint suggestions; failing.

**Comment by JerryFireman** [comment]
@terenc3t sorry I was not clear. the tests pass locally but I have  not updated the PR. I wanted to check if there was anything else I need to do before updating the PR. It sounds like you are saying I should go ahead and update, is that right?

**Comment by terenc3t** [comment]
Correct!

**Comment by JerryFireman** [comment]
@terenc3t Hi Terence, linter passes now. After fetching latest updates from Prysm, local unit test fails: "cannot find package "github.com/prysmaticlabs/prysm/contracts/validator-registration-contract". I have not touched anything related to this. Should I try to fix it or can I ignore it? I have pushed my latest code.

**Comment by JerryFireman** [comment]
@terenc3t unit test now works locally but fails here. i do not see anything in logs that has to do with me. can you please advise? thanks for your help!

**Pull request merged**
