### PR TITLE
Check Validator Status Before Fetching Assignment

### PR DESCRIPTION
**Pull request by terenc3t**
This PR added check for validator status before fetching for assignment, if a validator's status is "exited or "slashed_exited" then we **stop** validator client...

### CODE REVIEW

**Comment by prestonvanloon** [comment]
This conflicts with #2025 where validator assignments will return the validator status in the assignments response.

**Comment by terenc3t** [comment]
> This conflicts with #2025 where validator assignments will return the validator status in the assignments response.

Happy to build on top of a #2025 PR if there's one. Have we merged a #2025 PR where assignment also returns validator status? if not, do we have an ETA?

**Comment by prestonvanloon** [comment]
#2069 is the last part of #2025

**Comment by terenc3t** [comment]
Sounds good, let's merge #2069 in first then. Marking this as blocked by #2069

**Pull request closed without merging**
