### PR TITLE
Revert "Release Skip Slot Cache to All (#5280)"

### PR DESCRIPTION
**Pull request by nisdas**
This reverts commit f385a1dea6a154bf251cd991bc07b9117130d0e1.

**What type of PR is this?**

Reversion of #5280 

**What does this PR do? Why is it needed?**

This flag was released to be the default for all nodes. However this initially caused issues 
when syncing due to states being kept in the cache and not being released. In syncing
there will always be skipped slots, so this cache constantly held states. 

Also after regular sync, this cache continued to hold onto states in the normal course of
processing blocks. This causes larger than necessary memory consumption. While this is fine for prysmatic internally, the average user does not have much use for the cache. Our Hash Tree Root is much faster than previously, when the cache was initially created. If any user does need to use this cache, they can always use it with the flag.

**Which issues(s) does this PR fix?**
N.A

**Other notes for review**
N.A

### CODE REVIEW

**Comment by rauljordan** [comment]
Build fais

**Comment by prestonvanloon** [comment]
Skip slot cache was supposed to be disabled for init sync. What went wrong?

**Comment by rauljordan** [comment]
@nisdas thoughts on closing and instead opening a separate PR that implements one of the ideas outlined above?

**Comment by nisdas** [comment]
Closing this to implement a skip slot cache which caches at checkpoints instead of very slot.

**Pull request closed without merging**
