### PR TITLE
Migration to Bolt (Part 1)

### PR DESCRIPTION
**Pull request by rawfalafel**
**This is not yet ready for review**

Database comparison doc: https://docs.google.com/document/d/1KBTNm2XHkxyIX6zhMZvjOg6xALHiV8sgdNZPQsgeyCI/edit?usp=sharing

This migrates the database used in the beacon chain from leveldb to bolt. Migration of the validator client will be the next PR.

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Is this replacing leveldb or add another database implementation by bolt?

Are you introducing a flag to choose database backends?

Can you add a link to your design doc?

**Comment by rawfalafel** [comment]
> Is this replacing leveldb or add another database implementation by bolt?

Yea, this is going to completely replace leveldb.

> Are you introducing a flag to choose database backends?

Nope, I didn't make compatibility with multiple databases a requirement.

> Can you add a link to your design doc?

Yep!

**Comment by rawfalafel** [comment]
> Can we maintain extensibility with our database backends?

We can, what kind of databases did you want to maintain extensibility for?

**Comment by prestonvanloon** [comment]
At this point, we aren't sure of all of the use cases.

I'm imagining at least these two:
1) Local filesystem type KV store (like leveldb, etc)
2) External (shared) database, probably another KV store of some kind. Redis might be a good example.

For the latter use case, I am just thinking of redundant configurations. Imagine you have n+3 nodes because you need high availability. An optimization might be to use some centralize/shared database, if performance allowed. Restarting nodes, especially on ephemeral environments, might be improved if they didn't have to resync redundant data.

**Comment by rawfalafel** [comment]
> Local filesystem type KV store (like leveldb, etc)

Conforming to leveldb's API (`has`, `get`, `put`) would mean compromising elsewhere. We wouldn't be able to take advantage of boltdb transactions, and we wouldn't be able to switch to a relational or document oriented database.

> External (shared) database, probably another KV store of some kind. Redis might be a good example.

I think this would be pretty interesting. This might also open up possibilities for different setups, for example where validator connect directly to the database instead of the beacon chain.

What if I abstract database operations into its own class, so that in the future if we want to support different databases we can define an interface that can be implemented for any DB? Example:
```
type BeaconChainDB interface {
   createGenesisBlock() error
   createState() error
   saveBlock(*types.Block) error
   getBlock([32]byte) *types.Block
}
```

**Comment by prestonvanloon** [comment]
That sounds like a good approach to me. As long as the methods are agnostic to the underlying database then we should be OK to support multiple implementations. Even if the interface is quite larger than get/has/put/del.

**Comment by rawfalafel** [comment]
I'm going to split htis into smaller PRs

**Pull request closed without merging**
