### PR TITLE
Updates go.sum

### PR DESCRIPTION
**Pull request by farazdagi**
**What type of PR is this?**

Other

**What does this PR do? Why is it needed?**
- Updates `go.sum` after `go mod tidy` run

**Other notes for review**
- It is probably a good idea to have this added as pre-merge check (just as we have with `go fmt`), otherwise we will have similar PRs from time to time.

### CODE REVIEW

**Comment by nisdas** [comment]
@farazdagi what do you think about adding the go tidy check to this PR ?

**Comment by farazdagi** [comment]
> @farazdagi what do you think about adding the go mod tidy check to this PR ?

Will do!

**Comment by terencechain** [comment]
Oops sorry. I merged this and just saw it went back to in-progress : (

Feel free to open a new one with go mod tidy check, I'll help to merge that

**Comment by farazdagi** [comment]
No probs. Will open a new one :)

**Pull request merged**
