### PR TITLE
SlotToTime helper

### PR DESCRIPTION
**Pull request by prestonvanloon**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

It's helpful for time related functions

**Which issues(s) does this PR fix?**

N/A

**Other notes for review**

This will make #5708 easier

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Looks like its failing a test. Probably test setup

**Comment by prestonvanloon** [comment]
Looks like overflow! Fixing

**Comment by terencechain** [comment]
`TestStore_OnBlock/block_is_from_the_future` is failing still

**Comment by prestonvanloon** [comment]
Fixed finally

**Pull request merged**
