### PR TITLE
Dynamic wallet scan

### PR DESCRIPTION
**Pull request by alonmuroch**
Add the ability to dynamically add/ remove accounts for the wallet key manager by simply dropping/ removing account files from the wallet folder.

This covers issue https://github.com/prysmaticlabs/prysm/issues/5202

### CODE REVIEW

**Comment by terencechain** [comment]
Just some back ground, @prestonvanloon and I are working on a design to revamp validator key mgmt. Let's hold off to merge this until we have a clear direction on that front

**Comment by alonmuroch** [comment]
@terencechain would love to be a part of it..

**Comment by terencechain** [comment]
> @terencechain would love to be a part of it..

Great. Will loop you in when the design is ready

**Comment by alonmuroch** [comment]
@terencechain anywhere I can read up about future plans?

**Comment by terencechain** [comment]
> @terencechain anywhere I can read up about future plans?

We haven't made progress on this yet

**Pull request closed without merging**
