### PR TITLE
Integrate Raven for validator privacy 

### PR DESCRIPTION
**Pull request by rairyx**
[Raven](https://github.com/rairyx/raven) is an anonymous message broadcasting protocol based on Dandelion++ and libp2p, it can provide protection against deanonymization attacks thereby DoS attacks in which network adversary links transaction/block/attestation to IP addresses for validator with reasonable latency.   

Changes:
Replace go-libp2p-pubsub with rairyx/go-libp2p-pubsub for message broadcasting

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Hey @rairyx! Thanks for this patch. Is there any way we can toggle this optionally? 

I am a bit concerned about the drift between your fork and libp2p's implementation. We would consider this patch as an opt-in functionality using an experimental feature flag, but we cannot accept using Raven as the default without thorough testing. 

Our typical feature workflow goes as follows:
- Implement feature with opt-in feature flag.
- Run feature flag in Prylabs' experimental subset of testnet beacon nodes
- Monitor and evaluate success metrics of the feature
- Enable the flag for all of Prylabs' nodes
- Invert the flag to be opt-out 
- Remove the feature flag entirely, effectively releasing the feature to all users with no opt-out.

See https://pkg.go.dev/github.com/prysmaticlabs/prysm/shared/featureconfig?tab=doc

**Comment by rairyx** [comment]
> How widely adopted is Raven?
> 
> I think a good compromise here is to use a flag that enables toggling between raven and the formal
I think a flag to toggle this feature is possible, I'll look into it, thanks for the feedback @terencechain @prestonvanloon

**Comment by rairyx** [comment]
I looked into the feature flags, the only problem is this feature is implemented as a module(https://github.com/rairyx/go-libp2p-pubsub), using flag to conditionally import Raven module vs. formal libp2p module is bit tricky, any ideas?

**Comment by prestonvanloon** [comment]
Could Raven be another pubsub router? We have floodsub, gossipsub, and randomsub. It would be trivial to choose between gossipsub and raven at runtime via feature flags.

**Comment by rairyx** [comment]
@prestonvanloon Yeah make sense, it will take some time to rewrite it.
@nisdas thanks for the feedback, I'll look into the networking spec and try getting Raven included

**Comment by rauljordan** [comment]
Closing this PR for now @rairyx looking forward to seeing this suggested in the eth2 specs repo and following the discussion from there. If the spec adopts it, then we can consider this as a feature in Prysm.

**Pull request closed without merging**
