### PR TITLE
Replace ioutil with io and os

### PR DESCRIPTION
**Pull request by estensen**
**What type of PR is this?**

Cleanup

**What does this PR do? Why is it needed?**

From Go 1.16 the same functionality in `ioutil` is provided by the `io` and `os` packages.

### CODE REVIEW

**Comment by prestonvanloon** [comment]
This does not build. Please fix build issues. Thanks!

**Comment by estensen** [comment]
Will fix!

Is there an easy way of running all tests locally with bazel?

**Comment by prestonvanloon** [comment]
> Will fix!
> 
> Is there an easy way of running all tests locally with bazel?

Easiest way to _build_ everything is `bazel build //...`. You can test everything that way as well like `bazel test //...`

Sometimes, I use this command to run things that are affected by the code that I changed
```
git diff --name-only --diff-filter=MA origin/develop | grep .go$ | grep -v pb.go$ | sed -z 's/\n/ union /g;s/ union $/\n/' | xargs -I{} bazel query "{}" | sed -z 's/\n/ union /g;s/ union $/\n/' | xargs -I{} bazel query 'rdeps(//..., {})' |  xargs -t bazel build
```

You could probably find your build errors with go only as well `go build ./...`

**Comment by estensen** [comment]
Can't get your magic command to work, but that's probably because `sed` is a little different on my machine 😛  Had some problems with that in the past. Not sure why, running vanilla macOS Monterey.

```
$ git diff --name-only --diff-filter=MA origin/develop | grep .go$ | grep -v pb.go$ | sed -z 's/\n/ union /g;s/ union $/\n/' | xargs -I{} bazel query "{}" | sed -z 's/\n/ union /g;s/ union $/\n/' | xargs -I{} bazel query 'rdeps(//..., {})' |  xargs -t bazel build
sed: illegal option -- z
```

**Comment by estensen** [comment]
I don't agree with DeepSource that I introduced performance issues. I think it just triggered since I touched the file.

I don't think those issues should be fixed in this PR, but I can create another one and rebase this on top if you want?

**Comment by prestonvanloon** [comment]
> Can't get your magic command to work, but that's probably because `sed` is a little different on my machine 😛 Had some problems with that in the past. Not sure why, running vanilla macOS Monterey.
> 
> ```
> $ git diff --name-only --diff-filter=MA origin/develop | grep .go$ | grep -v pb.go$ | sed -z 's/\n/ union /g;s/ union $/\n/' | xargs -I{} bazel query "{}" | sed -z 's/\n/ union /g;s/ union $/\n/' | xargs -I{} bazel query 'rdeps(//..., {})' |  xargs -t bazel build
> sed: illegal option -- z
> ```

Oh yeah, sorry, I don't use Mac.

We can ignore existing deepsource issues if they are out of scope. Thanks so much!

**Review by prestonvanloon — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
