### PR TITLE
fixed depth check for SparseMerkleTrie object

### PR DESCRIPTION
**Pull request by infosecual**
**What type of PR is this?**
Bug fix

**What does this PR do? Why is it needed?**
Nosy ([golang project fuzzer](https://github.com/infosecual/nosy)) found 2 separate types of panics in 8 functions due to the same underlying issue:

1. `panic: runtime error: index out of range [100] with length 100` triggered in:
    - `SparseMerkleTrie.Copy()`
    - `SparseMerkleTrie.HashTreeRoot()`
    - `SparseMerkleTrie.Insert()`
    - `SparseMerkleTrie.Items()`
    - `SparseMerkleTrie.NumOfItems()`
    - `SparseMerkleTrie.ToProto()`
    - `SparseMerkleTrie.validate()`
2. `panic: runtime error: integer divide by zero` triggered in:
    - `SparseMerkleTrie.MerkleProof()`

The issue it that the `SparseMerkleTrie` object's depth check has an off-by-one in SparseMerkleTrie.validate() and does not exist in `GenerateTrieFromItems()` which are the two possible code paths that can produce the `SparseMerkleTrie` object (`validate()` is called to sanitize tries created from protobufs in `CreateTrieFromProto()`).

In the case of `SparseMerkleTrie.validate()`, [there is a check](https://github.com/prysmaticlabs/prysm/blob/9c6a1331cfcb655ad1b901091eb1ec011500ca26/container/trie/sparse_merkle.go#L60) that the trie's depth does not exceed 64. This is done to prevent an overflow:
```go
func (m *SparseMerkleTrie) validate() error {
	if len(m.branches) == 0 {
		return errors.New("no branches")
	}
	if len(m.branches[len(m.branches)-1]) == 0 {
		return errors.New("invalid branches provided")
	}
	if m.depth >= uint(len(m.branches)) {
		return errors.New("depth is greater than or equal to number of branches")
	}
	if m.depth >= 64 {
		return errors.New("depth exceeds 64") // PowerOf2 would overflow.
	}

	return nil
}
```
Unfortunately this is not sufficient to prevent an overflow as the underlying datatype of the merkle trie's index is a uint64, which can only hold a depth of (2^64)-1 and will overflow if raised to a depth of 64. This will cause a divide-by-0 panic in [SparseMerkleTrie.MerkleProof()](https://github.com/prysmaticlabs/prysm/blob/9c6a1331cfcb655ad1b901091eb1ec011500ca26/container/trie/sparse_merkle.go#L176):
```go
for i := uint(0); i < m.depth; i++ {
	subIndex := (merkleIndex / (1 << i)) ^ 1 // div-by-0 panic when i == 63, bit shifted out of the register
	if subIndex < uint(len(m.branches[i])) {
		item := bytesutil.ToBytes32(m.branches[i][subIndex])
		proof[i] = item[:]
	} else {
		proof[i] = ZeroHashes[i][:]
	}
}
```

**Fixes**

Changing the conditional in `SparseMerkleTrie.validate()` to `if m.depth >= 63` will fix both the divide-by-0 and adding the same check to `GenerateTrieFromItems()` will prevent the array indexing panics. The theoretical max depth of these tries is 64, which cannot be handled by prysm currently with this fix. Unfortunately the alternative would require changing/enlarging the `uint64` `index` which would cause a performance hit, and will not be needed for honest clients on mainnet currently.

I did add a little more info about the depth constraint to the error message that is produced. I am happy to explorer other error messages or other ways to fix this.

### CODE REVIEW

**Review by nisdas — COMMENTED** [review]
This is a great catch by the fuzzer ! Do you mind adding in regression tests for these specific cases ?

**Comment by potuz** [comment]
Wow! cc @prestonvanloon who may care about why our fuzzers didn't catch these

**Comment by infosecual** [comment]
> This is a great catch by the fuzzer ! Do you mind adding in regression tests for these specific cases ?

re: @nisdas's request- Yes, I will add some regression tests today :)

**Comment by infosecual** [comment]
> Wow! cc @prestonvanloon who may care about why our fuzzers didn't catch these

FWIW Nosy is a breadth first fuzzer that basically creates a bunch of fuzzing harnesses automatically using the target repo's AST. Because of this methodology a good number of the panics it finds may be unreachable in regular node operation. So, the first set of panics (eg. array index issues) may not ever be possible in production, especially if your fuzzers never tried to create a SparseMerkleTrie with a depth larger than DEPOSIT_CONTRACT_TREE_DEPTH (currently 32 on mainnet).

I created Nosy to increase code coverage without the dev working too hard but the drawback is that it can often provide false positives (eg. technically unreachable code). I will make PRs in cases like these where at least one path is reachable or a future update could make the bug live. Having said that please don't use them to judge your current fuzzers which do get good coverage :)

Nosy in its current form support's automatic fuzzing of 8,237 function in prysm's capella branch. [Here](https://gist.github.com/infosecual/fdeeb034ad4fda2b0e025fa573ffc8ba) is an example harness for the package `prysm/beacon-chain/p2p/peers/scorers`.

**Comment by nisdas** [comment]
@infosecual Can you point this to `develop` , since this isn't specific to capella.

**Comment by infosecual** [comment]
Since I originally created my branch from the capella base I think the easiest way for me to do this is to create a separate fork of develop and make a new PR.

**Comment by infosecual** [comment]
I just opened #11778 so I am closing this PR as we can track this

**Comment by infosecual** [comment]
I created #11778 with develop as the base branch so I closed this PR.

**Pull request closed without merging**
