### PR TITLE
Update Deps For Capella

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Dependency Update

**What does this PR do? Why is it needed?**

This updates our go-ethereum dependency to v1.11.2 and lighthouse dependency to v3.5.0 .  These are capella compatible versions for both clients which should allow us to test them out properly in our E2E tests.

**Which issues(s) does this PR fix?**

N.A

**Other notes for review**

### CODE REVIEW

**Review by rkapka — DISMISSED** [review]

**Review by rkapka — APPROVED** [review]

**Comment by prestonvanloon** [comment]
Blocked by https://github.com/bazelbuild/rules_go/issues/3411

**Comment by prestonvanloon** [comment]
Unblocked by 19c374117bf907e3aabe946a685247aac1997983

**Review by prestonvanloon — APPROVED** [review]
LGTM, I applied a workaround for zstd

**Comment by prestonvanloon** [comment]
Tests fail: 
> assertions.go:103: check_transition_config_test.go:243 Unexpected error: got an unexpected error in JSON-RPC response: missing required field 'parentHash' for Header

**Comment by nisdas** [comment]
It seems like this was because of this PR: 
https://github.com/ethereum/go-ethereum/pull/26723

**Review by prestonvanloon — APPROVED** [review]
I'm not a fan of the hacky patch, but I am guessing it will break again on their next release?

**Comment by nisdas** [comment]
> I'm not a fan of the hacky patch, but I am guessing it will break again on their next release?

I dont think so, this seems like it was because the geth team fixed a long-standing bug and our test relied on that bug to pass. I don't expect this to break anymore. In anycase this test is testing a function that is cosmetic and deprecated after the merge, so not a big issue.

**Pull request merged**
