### PR TITLE
Add --p2p-host-dns flag to specify p2p external DNS

### PR DESCRIPTION
**Pull request by timmyers**
# Description

**Write why you are making the changes in this pull request**
Add an option to specify a DNS address for p2p external addressing.  This is useful for cases when the nodes may not be accessible by a public static IP address, but can be by a domain name.

**Write a summary of the changes you are making**
Add `--p2p-host-dns` flag to allow setting a domain name for the p2p external address.

**Link anything that would be helpful or relevant to the reviewers**

### CODE REVIEW

**Comment by mcdee** [comment]
What happens if both a host name and IP address are supplied?  Should these be mutually exclusive options?

**Comment by timmyers** [comment]
Yes probably, would just `log.Fatalf` in `buildOptions()` be the best way to error out in that case?

**Comment by mcdee** [comment]
That should work, yes.

**Comment by nisdas** [comment]
We dont need to make it a fatal condition, if both a dns address and a host ip is supplied they can just be added to libp2p's address factory. Libp2p will look at each multiaddress separately so it shouldnt be an issue

**Comment by mcdee** [comment]
Would this not cause problems with inbound connections being duplicated, or is libp2p intelligent enough to work out that the two addresses are the same?

**Comment by timmyers** [comment]
I am not sure.  Maybe the likelihood of passing both parameters is low enough though that it is okay to leave the option open for experimentation if anyone chooses to?

**Comment by prestonvanloon** [comment]
The peer often broadcasts many multiaddresses and some of those are not dialable, that is acceptable practice. Sometimes the peer wants to broadcast its local area network for any local peers. Having DNS and IP based addresses is OK.

**Pull request merged**
