### PR TITLE
Remove duty countdown flag

### PR DESCRIPTION
**Pull request by terencechain**
This was primarily created for fun back in the old testnet days. I doubt anyone is using it. As for the validator client code base, I'd love to keep only the critical code piece in there so none of these fun / experimental features that no one uses

### CODE REVIEW

**Review by rkapka — APPROVED** [review]

**Comment by Tadouh** [comment]
I actually use this flag and really hate to see it go. This is the easiest way to know when your validator is going to submit new attestations and or proposals. I use this to know when I can restart the clients without interrupting my duties. This should be implemented in some fashion by default so we know when our validator is about to have a duty.

**Comment by terencechain** [comment]
> I actually use this flag and really hate to see it go. This is the easiest way to know when your validator is going to submit new attestations and or proposals. I use this to know when I can restart the clients without interrupting my duties. This should be implemented in some fashion by default so we know when our validator is about to have a duty.

Thanks for bringing this up. Happy to implement this feature for `prysmctl` utility or some other tools

**Comment by Tadouh** [comment]
Thanks! Without this, its a guessing game as to when one can restart without missing duties. Is there any way to see this kind of info by maybe turning the verbosity up ?

**Comment by terencechain** [comment]
> Thanks! Without this, its a guessing game as to when one can restart without missing duties. Is there any way to see this kind of info by maybe turning the verbosity up ?

Do you see this log? it's a default INFO log on validator client:
```
[2022-08-22 18:45:59]  INFO validator: Attestation schedule attesterDutiesAtSlot=1 pubKeys=[0xabcd] slot=4532944 slotInEpoch=16 totalAttestersInEpoch=1
```

`slotInEpoch` is what to look for. You have until `12s * slotInEpoch` until the duity is performed. In the above example 16 * 12s is roughly 3 mins

**Comment by Tadouh** [comment]
Thanks for pointing that out terrance. I would look at that before and wish there was some way to know how long until the attestation was. I will use this in the future once the depreciation kicks in.

**Pull request merged**
